// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myip_v1_unoptimized_HLS_myip_v1_unoptimized_HLS,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.972000,HLS_SYN_LAT=669,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=331,HLS_SYN_LUT=1029,HLS_VERSION=2023_2}" *)

module myip_v1_unoptimized_HLS (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
reg   [5:0] A_address0;
reg    A_ce0;
reg    A_we0;
wire   [7:0] A_q0;
reg   [5:0] A_1_address0;
reg    A_1_ce0;
reg    A_1_we0;
wire   [7:0] A_1_q0;
reg   [5:0] A_2_address0;
reg    A_2_ce0;
reg    A_2_we0;
wire   [7:0] A_2_q0;
reg   [5:0] A_3_address0;
reg    A_3_ce0;
reg    A_3_we0;
wire   [7:0] A_3_q0;
reg   [5:0] A_4_address0;
reg    A_4_ce0;
reg    A_4_we0;
wire   [7:0] A_4_q0;
reg   [5:0] A_5_address0;
reg    A_5_ce0;
reg    A_5_we0;
wire   [7:0] A_5_q0;
reg   [5:0] A_6_address0;
reg    A_6_ce0;
reg    A_6_we0;
wire   [7:0] A_6_q0;
reg   [5:0] A_7_address0;
reg    A_7_ce0;
reg    A_7_we0;
wire   [7:0] A_7_q0;
reg   [5:0] C_0_address0;
reg    C_0_ce0;
reg    C_0_we0;
wire   [7:0] C_0_q0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_done;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_idle;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_ready;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_d0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_d0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_S_AXIS_TREADY;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_done;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_idle;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_ready;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_S_AXIS_TREADY;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_7_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_7_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_6_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_6_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_5_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_5_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_4_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_4_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_3_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_3_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_2_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_2_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_1_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_1_out_ap_vld;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_out;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_out_ap_vld;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_done;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_idle;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_ready;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_1_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_1_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_2_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_2_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_3_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_3_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_4_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_4_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_5_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_5_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_6_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_6_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_7_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_7_ce0;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_ce0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_we0;
wire   [7:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_d0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_done;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_idle;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_ready;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TREADY;
wire   [5:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_C_0_address0;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_C_0_ce0;
wire   [31:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TDATA;
wire    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID;
wire   [3:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TKEEP;
wire   [3:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TSTRB;
wire   [0:0] grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TLAST;
reg    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [10:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state11;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
wire    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start_reg = 1'b0;
#0 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start_reg = 1'b0;
#0 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start_reg = 1'b0;
end

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_address0),
    .ce0(A_ce0),
    .we0(A_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_d0),
    .q0(A_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_1_address0),
    .ce0(A_1_ce0),
    .we0(A_1_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_d0),
    .q0(A_1_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_2_address0),
    .ce0(A_2_ce0),
    .we0(A_2_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_d0),
    .q0(A_2_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_3_address0),
    .ce0(A_3_ce0),
    .we0(A_3_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_d0),
    .q0(A_3_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_4_address0),
    .ce0(A_4_ce0),
    .we0(A_4_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_d0),
    .q0(A_4_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_5_address0),
    .ce0(A_5_ce0),
    .we0(A_5_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_d0),
    .q0(A_5_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_6_address0),
    .ce0(A_6_ce0),
    .we0(A_6_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_d0),
    .q0(A_6_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_7_address0),
    .ce0(A_7_ce0),
    .we0(A_7_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_d0),
    .q0(A_7_q0)
);

myip_v1_unoptimized_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
C_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(C_0_address0),
    .ce0(C_0_ce0),
    .we0(C_0_we0),
    .d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_d0),
    .q0(C_0_q0)
);

myip_v1_unoptimized_HLS_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start),
    .ap_done(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_done),
    .ap_idle(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_idle),
    .ap_ready(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .A_7_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_address0),
    .A_7_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_ce0),
    .A_7_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_we0),
    .A_7_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_d0),
    .A_6_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_address0),
    .A_6_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_ce0),
    .A_6_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_we0),
    .A_6_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_d0),
    .A_5_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_address0),
    .A_5_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_ce0),
    .A_5_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_we0),
    .A_5_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_d0),
    .A_4_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_address0),
    .A_4_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_ce0),
    .A_4_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_we0),
    .A_4_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_d0),
    .A_3_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_address0),
    .A_3_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_ce0),
    .A_3_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_we0),
    .A_3_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_d0),
    .A_2_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_address0),
    .A_2_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_ce0),
    .A_2_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_we0),
    .A_2_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_d0),
    .A_1_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_address0),
    .A_1_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_ce0),
    .A_1_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_we0),
    .A_1_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_d0),
    .A_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_address0),
    .A_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_ce0),
    .A_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_we0),
    .A_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice)
);

myip_v1_unoptimized_HLS_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start),
    .ap_done(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_done),
    .ap_idle(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_idle),
    .ap_ready(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice),
    .B_7_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_7_out),
    .B_7_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_7_out_ap_vld),
    .B_6_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_6_out),
    .B_6_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_6_out_ap_vld),
    .B_5_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_5_out),
    .B_5_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_5_out_ap_vld),
    .B_4_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_4_out),
    .B_4_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_4_out_ap_vld),
    .B_3_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_3_out),
    .B_3_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_3_out_ap_vld),
    .B_2_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_2_out),
    .B_2_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_2_out_ap_vld),
    .B_1_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_1_out),
    .B_1_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_1_out_ap_vld),
    .B_out(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_out),
    .B_out_ap_vld(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_out_ap_vld)
);

myip_v1_unoptimized_HLS_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start),
    .ap_done(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_done),
    .ap_idle(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_idle),
    .ap_ready(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_ready),
    .A_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_address0),
    .A_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_ce0),
    .A_q0(A_q0),
    .A_1_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_1_address0),
    .A_1_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_2_address0),
    .A_2_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_3_address0),
    .A_3_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_3_ce0),
    .A_3_q0(A_3_q0),
    .A_4_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_4_address0),
    .A_4_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_4_ce0),
    .A_4_q0(A_4_q0),
    .A_5_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_5_address0),
    .A_5_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_5_ce0),
    .A_5_q0(A_5_q0),
    .A_6_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_6_address0),
    .A_6_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_6_ce0),
    .A_6_q0(A_6_q0),
    .A_7_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_7_address0),
    .A_7_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_7_ce0),
    .A_7_q0(A_7_q0),
    .zext_ln74(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_out),
    .zext_ln74_1(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_1_out),
    .zext_ln74_2(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_2_out),
    .zext_ln74_3(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_3_out),
    .zext_ln74_4(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_4_out),
    .zext_ln74_5(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_5_out),
    .zext_ln74_6(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_6_out),
    .zext_ln74_7(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_B_7_out),
    .C_0_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_address0),
    .C_0_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_ce0),
    .C_0_we0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_we0),
    .C_0_d0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_d0)
);

myip_v1_unoptimized_HLS_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6 grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start),
    .ap_done(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_done),
    .ap_idle(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_idle),
    .ap_ready(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_ready),
    .M_AXIS_TREADY(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TREADY),
    .C_0_address0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_C_0_address0),
    .C_0_ce0(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_C_0_ce0),
    .C_0_q0(C_0_q0),
    .M_AXIS_TDATA(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TDATA),
    .M_AXIS_TVALID(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID),
    .M_AXIS_TKEEP(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TSTRB),
    .M_AXIS_TLAST(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TLAST)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TDATA),
    .vld_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TKEEP),
    .vld_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TSTRB),
    .vld_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

myip_v1_unoptimized_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TLAST),
    .vld_in(grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_ready == 1'b1)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_ready == 1'b1)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_ready == 1'b1)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_ready == 1'b1)) begin
            grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_1_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_1_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_address0;
    end else begin
        A_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_1_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_1_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_ce0;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_1_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_1_we0;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_2_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_2_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_address0;
    end else begin
        A_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_2_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_2_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_ce0;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_2_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_2_we0;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_3_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_3_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_address0;
    end else begin
        A_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_3_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_3_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_ce0;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_3_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_3_we0;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_4_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_4_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_address0;
    end else begin
        A_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_4_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_4_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_ce0;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_4_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_4_we0;
    end else begin
        A_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_5_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_5_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_address0;
    end else begin
        A_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_5_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_5_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_ce0;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_5_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_5_we0;
    end else begin
        A_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_6_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_6_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_address0;
    end else begin
        A_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_6_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_6_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_ce0;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_6_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_6_we0;
    end else begin
        A_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_7_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_7_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_address0;
    end else begin
        A_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_7_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_7_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_ce0;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_7_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_7_we0;
    end else begin
        A_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        A_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_A_we0;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        C_0_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_C_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_0_address0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_address0;
    end else begin
        C_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        C_0_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_C_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        C_0_ce0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_ce0;
    end else begin
        C_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        C_0_we0 = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_C_0_we0;
    end else begin
        C_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        S_AXIS_TREADY_int_regslice = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_S_AXIS_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        S_AXIS_TREADY_int_regslice = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_S_AXIS_TREADY;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign M_AXIS_TVALID_int_regslice = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TVALID;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_59_1_fu_126_ap_start_reg;

assign grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_64_2_fu_146_ap_start_reg;

assign grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_70_3_fu_166_ap_start_reg;

assign grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_M_AXIS_TREADY = (ap_CS_fsm_state10 & M_AXIS_TREADY_int_regslice);

assign grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start = grp_myip_v1_unoptimized_HLS_Pipeline_VITIS_LOOP_81_6_fu_187_ap_start_reg;


reg find_kernel_block = 0;
// synthesis translate_off
`include "myip_v1_unoptimized_HLS_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myip_v1_unoptimized_HLS

