// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_VITIS_LOOP_72_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        A_4_address0,
        A_4_ce0,
        A_4_q0,
        A_5_address0,
        A_5_ce0,
        A_5_q0,
        A_6_address0,
        A_6_ce0,
        A_6_q0,
        A_7_address0,
        A_7_ce0,
        A_7_q0,
        conv3_i11_i,
        conv3_i11_i_1,
        conv3_i11_i_2,
        conv3_i11_i_3,
        conv3_i11_i_4,
        conv3_i11_i_5,
        conv3_i11_i_6,
        conv3_i11_i_7,
        C_0_address0,
        C_0_ce0,
        C_0_we0,
        C_0_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [5:0] A_1_address0;
output   A_1_ce0;
input  [7:0] A_1_q0;
output  [5:0] A_2_address0;
output   A_2_ce0;
input  [7:0] A_2_q0;
output  [5:0] A_3_address0;
output   A_3_ce0;
input  [7:0] A_3_q0;
output  [5:0] A_4_address0;
output   A_4_ce0;
input  [7:0] A_4_q0;
output  [5:0] A_5_address0;
output   A_5_ce0;
input  [7:0] A_5_q0;
output  [5:0] A_6_address0;
output   A_6_ce0;
input  [7:0] A_6_q0;
output  [5:0] A_7_address0;
output   A_7_ce0;
input  [7:0] A_7_q0;
input  [7:0] conv3_i11_i;
input  [7:0] conv3_i11_i_1;
input  [7:0] conv3_i11_i_2;
input  [7:0] conv3_i11_i_3;
input  [7:0] conv3_i11_i_4;
input  [7:0] conv3_i11_i_5;
input  [7:0] conv3_i11_i_6;
input  [7:0] conv3_i11_i_7;
output  [5:0] C_0_address0;
output   C_0_ce0;
output   C_0_we0;
output  [7:0] C_0_d0;

reg ap_idle;
reg A_ce0;
reg A_1_ce0;
reg A_2_ce0;
reg A_3_ce0;
reg A_4_ce0;
reg A_5_ce0;
reg A_6_ce0;
reg A_7_ce0;
reg C_0_ce0;
reg C_0_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln72_fu_277_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [15:0] conv3_i11_i_7_cast_fu_237_p1;
reg   [15:0] conv3_i11_i_7_cast_reg_418;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] conv3_i11_i_6_cast_fu_241_p1;
reg   [15:0] conv3_i11_i_6_cast_reg_423;
wire   [15:0] conv3_i11_i_5_cast_fu_245_p1;
reg   [15:0] conv3_i11_i_5_cast_reg_428;
wire   [15:0] conv3_i11_i_4_cast_fu_249_p1;
reg   [15:0] conv3_i11_i_4_cast_reg_433;
wire   [15:0] conv3_i11_i_3_cast_fu_253_p1;
reg   [15:0] conv3_i11_i_3_cast_reg_438;
wire   [15:0] conv3_i11_i_2_cast_fu_257_p1;
reg   [15:0] conv3_i11_i_2_cast_reg_443;
wire   [15:0] conv3_i11_i_1_cast_fu_261_p1;
reg   [15:0] conv3_i11_i_1_cast_reg_448;
wire   [15:0] conv3_i11_i_cast_fu_265_p1;
reg   [15:0] conv3_i11_i_cast_reg_453;
wire   [63:0] zext_ln72_fu_289_p1;
reg   [63:0] zext_ln72_reg_462;
reg   [63:0] zext_ln72_reg_462_pp0_iter1_reg;
reg   [63:0] zext_ln72_reg_462_pp0_iter2_reg;
reg   [63:0] zext_ln72_reg_462_pp0_iter3_reg;
wire   [15:0] mul_ln77_fu_322_p2;
wire   [15:0] mul_ln77_1_fu_331_p2;
wire   [15:0] mul_ln77_3_fu_340_p2;
wire   [15:0] mul_ln77_5_fu_349_p2;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_68;
wire   [6:0] add_ln72_fu_283_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
wire   [7:0] mul_ln77_fu_322_p0;
wire   [7:0] mul_ln77_fu_322_p1;
wire   [7:0] mul_ln77_1_fu_331_p0;
wire   [7:0] mul_ln77_1_fu_331_p1;
wire   [7:0] mul_ln77_3_fu_340_p0;
wire   [7:0] mul_ln77_3_fu_340_p1;
wire   [7:0] mul_ln77_5_fu_349_p0;
wire   [7:0] mul_ln77_5_fu_349_p1;
wire   [15:0] grp_fu_387_p3;
wire   [15:0] grp_fu_379_p3;
wire   [15:0] grp_fu_403_p3;
wire   [15:0] grp_fu_395_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln77_5_fu_358_p2;
(* use_dsp48 = "no" *) wire   [15:0] add_ln77_2_fu_354_p2;
wire   [15:0] sum_1_fu_362_p2;
wire   [7:0] grp_fu_379_p0;
wire   [7:0] grp_fu_379_p1;
wire   [7:0] grp_fu_387_p0;
wire   [7:0] grp_fu_387_p1;
wire   [7:0] grp_fu_395_p0;
wire   [7:0] grp_fu_395_p1;
wire   [7:0] grp_fu_403_p0;
wire   [7:0] grp_fu_403_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_379_p00;
wire   [15:0] grp_fu_387_p00;
wire   [15:0] grp_fu_395_p00;
wire   [15:0] grp_fu_403_p00;
wire   [15:0] mul_ln77_1_fu_331_p00;
wire   [15:0] mul_ln77_3_fu_340_p00;
wire   [15:0] mul_ln77_5_fu_349_p00;
wire   [15:0] mul_ln77_fu_322_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 i_fu_68 = 7'd0;
#0 ap_done_reg = 1'b0;
end

myip_v1_0_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U1(
    .din0(mul_ln77_fu_322_p0),
    .din1(mul_ln77_fu_322_p1),
    .dout(mul_ln77_fu_322_p2)
);

myip_v1_0_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U2(
    .din0(mul_ln77_1_fu_331_p0),
    .din1(mul_ln77_1_fu_331_p1),
    .dout(mul_ln77_1_fu_331_p2)
);

myip_v1_0_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U3(
    .din0(mul_ln77_3_fu_340_p0),
    .din1(mul_ln77_3_fu_340_p1),
    .dout(mul_ln77_3_fu_340_p2)
);

myip_v1_0_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U4(
    .din0(mul_ln77_5_fu_349_p0),
    .din1(mul_ln77_5_fu_349_p1),
    .dout(mul_ln77_5_fu_349_p2)
);

myip_v1_0_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_379_p0),
    .din1(grp_fu_379_p1),
    .din2(mul_ln77_fu_322_p2),
    .ce(1'b1),
    .dout(grp_fu_379_p3)
);

myip_v1_0_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_387_p0),
    .din1(grp_fu_387_p1),
    .din2(mul_ln77_1_fu_331_p2),
    .ce(1'b1),
    .dout(grp_fu_387_p3)
);

myip_v1_0_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_395_p0),
    .din1(grp_fu_395_p1),
    .din2(mul_ln77_3_fu_340_p2),
    .ce(1'b1),
    .dout(grp_fu_395_p3)
);

myip_v1_0_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_403_p0),
    .din1(grp_fu_403_p1),
    .din2(mul_ln77_5_fu_349_p2),
    .ce(1'b1),
    .dout(grp_fu_403_p3)
);

myip_v1_0_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln72_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_68 <= add_ln72_fu_283_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv3_i11_i_1_cast_reg_448[7 : 0] <= conv3_i11_i_1_cast_fu_261_p1[7 : 0];
        conv3_i11_i_2_cast_reg_443[7 : 0] <= conv3_i11_i_2_cast_fu_257_p1[7 : 0];
        conv3_i11_i_3_cast_reg_438[7 : 0] <= conv3_i11_i_3_cast_fu_253_p1[7 : 0];
        conv3_i11_i_4_cast_reg_433[7 : 0] <= conv3_i11_i_4_cast_fu_249_p1[7 : 0];
        conv3_i11_i_5_cast_reg_428[7 : 0] <= conv3_i11_i_5_cast_fu_245_p1[7 : 0];
        conv3_i11_i_6_cast_reg_423[7 : 0] <= conv3_i11_i_6_cast_fu_241_p1[7 : 0];
        conv3_i11_i_7_cast_reg_418[7 : 0] <= conv3_i11_i_7_cast_fu_237_p1[7 : 0];
        conv3_i11_i_cast_reg_453[7 : 0] <= conv3_i11_i_cast_fu_265_p1[7 : 0];
        zext_ln72_reg_462[6 : 0] <= zext_ln72_fu_289_p1[6 : 0];
        zext_ln72_reg_462_pp0_iter1_reg[6 : 0] <= zext_ln72_reg_462[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        zext_ln72_reg_462_pp0_iter2_reg[6 : 0] <= zext_ln72_reg_462_pp0_iter1_reg[6 : 0];
        zext_ln72_reg_462_pp0_iter3_reg[6 : 0] <= zext_ln72_reg_462_pp0_iter2_reg[6 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_2_ce0 = 1'b1;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_3_ce0 = 1'b1;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_4_ce0 = 1'b1;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_5_ce0 = 1'b1;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_6_ce0 = 1'b1;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_7_ce0 = 1'b1;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        C_0_ce0 = 1'b1;
    end else begin
        C_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        C_0_we0 = 1'b1;
    end else begin
        C_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln72_fu_277_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_68;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_1_address0 = zext_ln72_reg_462_pp0_iter1_reg;

assign A_2_address0 = zext_ln72_reg_462_pp0_iter1_reg;

assign A_3_address0 = zext_ln72_fu_289_p1;

assign A_4_address0 = zext_ln72_reg_462_pp0_iter1_reg;

assign A_5_address0 = zext_ln72_fu_289_p1;

assign A_6_address0 = zext_ln72_reg_462_pp0_iter1_reg;

assign A_7_address0 = zext_ln72_fu_289_p1;

assign A_address0 = zext_ln72_fu_289_p1;

assign C_0_address0 = zext_ln72_reg_462_pp0_iter3_reg;

assign C_0_d0 = {{sum_1_fu_362_p2[15:8]}};

assign add_ln72_fu_283_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign add_ln77_2_fu_354_p2 = (grp_fu_387_p3 + grp_fu_379_p3);

assign add_ln77_5_fu_358_p2 = (grp_fu_403_p3 + grp_fu_395_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv3_i11_i_1_cast_fu_261_p1 = conv3_i11_i_1;

assign conv3_i11_i_2_cast_fu_257_p1 = conv3_i11_i_2;

assign conv3_i11_i_3_cast_fu_253_p1 = conv3_i11_i_3;

assign conv3_i11_i_4_cast_fu_249_p1 = conv3_i11_i_4;

assign conv3_i11_i_5_cast_fu_245_p1 = conv3_i11_i_5;

assign conv3_i11_i_6_cast_fu_241_p1 = conv3_i11_i_6;

assign conv3_i11_i_7_cast_fu_237_p1 = conv3_i11_i_7;

assign conv3_i11_i_cast_fu_265_p1 = conv3_i11_i;

assign grp_fu_379_p0 = grp_fu_379_p00;

assign grp_fu_379_p00 = A_q0;

assign grp_fu_379_p1 = conv3_i11_i_cast_reg_453;

assign grp_fu_387_p0 = grp_fu_387_p00;

assign grp_fu_387_p00 = A_3_q0;

assign grp_fu_387_p1 = conv3_i11_i_3_cast_reg_438;

assign grp_fu_395_p0 = grp_fu_395_p00;

assign grp_fu_395_p00 = A_5_q0;

assign grp_fu_395_p1 = conv3_i11_i_5_cast_reg_428;

assign grp_fu_403_p0 = grp_fu_403_p00;

assign grp_fu_403_p00 = A_7_q0;

assign grp_fu_403_p1 = conv3_i11_i_7_cast_reg_418;

assign icmp_ln72_fu_277_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign mul_ln77_1_fu_331_p0 = mul_ln77_1_fu_331_p00;

assign mul_ln77_1_fu_331_p00 = A_2_q0;

assign mul_ln77_1_fu_331_p1 = conv3_i11_i_2_cast_reg_443;

assign mul_ln77_3_fu_340_p0 = mul_ln77_3_fu_340_p00;

assign mul_ln77_3_fu_340_p00 = A_4_q0;

assign mul_ln77_3_fu_340_p1 = conv3_i11_i_4_cast_reg_433;

assign mul_ln77_5_fu_349_p0 = mul_ln77_5_fu_349_p00;

assign mul_ln77_5_fu_349_p00 = A_6_q0;

assign mul_ln77_5_fu_349_p1 = conv3_i11_i_6_cast_reg_423;

assign mul_ln77_fu_322_p0 = mul_ln77_fu_322_p00;

assign mul_ln77_fu_322_p00 = A_1_q0;

assign mul_ln77_fu_322_p1 = conv3_i11_i_1_cast_reg_448;

assign sum_1_fu_362_p2 = (add_ln77_5_fu_358_p2 + add_ln77_2_fu_354_p2);

assign zext_ln72_fu_289_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    conv3_i11_i_7_cast_reg_418[15:8] <= 8'b00000000;
    conv3_i11_i_6_cast_reg_423[15:8] <= 8'b00000000;
    conv3_i11_i_5_cast_reg_428[15:8] <= 8'b00000000;
    conv3_i11_i_4_cast_reg_433[15:8] <= 8'b00000000;
    conv3_i11_i_3_cast_reg_438[15:8] <= 8'b00000000;
    conv3_i11_i_2_cast_reg_443[15:8] <= 8'b00000000;
    conv3_i11_i_1_cast_reg_448[15:8] <= 8'b00000000;
    conv3_i11_i_cast_reg_453[15:8] <= 8'b00000000;
    zext_ln72_reg_462[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln72_reg_462_pp0_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln72_reg_462_pp0_iter2_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln72_reg_462_pp0_iter3_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_VITIS_LOOP_72_3
