# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sunil/VivadoProjects/EE4218Labs/Lab4/integrated_coprocessor_v1/integrated_coprocessor_v1.srcs/sources_1/bd/design_1/ip/design_1_myip_v1_0_HLS_0_0/design_1_myip_v1_0_HLS_0_0.xci
# IP: The module: 'design_1_myip_v1_0_HLS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sunil/VivadoProjects/EE4218Labs/Lab4/integrated_coprocessor_v1/integrated_coprocessor_v1.gen/sources_1/bd/design_1/ip/design_1_myip_v1_0_HLS_0_0/constraints/myip_v1_0_HLS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_myip_v1_0_HLS_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/sunil/VivadoProjects/EE4218Labs/Lab4/integrated_coprocessor_v1/integrated_coprocessor_v1.srcs/sources_1/bd/design_1/ip/design_1_myip_v1_0_HLS_0_0/design_1_myip_v1_0_HLS_0_0.xci
# IP: The module: 'design_1_myip_v1_0_HLS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sunil/VivadoProjects/EE4218Labs/Lab4/integrated_coprocessor_v1/integrated_coprocessor_v1.gen/sources_1/bd/design_1/ip/design_1_myip_v1_0_HLS_0_0/constraints/myip_v1_0_HLS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_myip_v1_0_HLS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
