# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sunil/VivadoProjects/EE4218Labs/Project/MLP_NN_Project/MLP_NN_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_fifo_mm_s_0_2/design_1_axi_fifo_mm_s_0_2.xci
# IP: The module: 'design_1_axi_fifo_mm_s_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sunil/VivadoProjects/EE4218Labs/Project/MLP_NN_Project/MLP_NN_Project.gen/sources_1/bd/design_1/ip/design_1_axi_fifo_mm_s_0_2/design_1_axi_fifo_mm_s_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_fifo_mm_s_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/sunil/VivadoProjects/EE4218Labs/Project/MLP_NN_Project/MLP_NN_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_fifo_mm_s_0_2/design_1_axi_fifo_mm_s_0_2.xci
# IP: The module: 'design_1_axi_fifo_mm_s_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sunil/VivadoProjects/EE4218Labs/Project/MLP_NN_Project/MLP_NN_Project.gen/sources_1/bd/design_1/ip/design_1_axi_fifo_mm_s_0_2/design_1_axi_fifo_mm_s_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_fifo_mm_s_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
