// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myip_v1_0_HLS_Loop_VITIS_LOOP_92_3_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        A_dout,
        A_num_data_valid,
        A_fifo_cap,
        A_empty_n,
        A_read,
        A_1_dout,
        A_1_num_data_valid,
        A_1_fifo_cap,
        A_1_empty_n,
        A_1_read,
        A_2_dout,
        A_2_num_data_valid,
        A_2_fifo_cap,
        A_2_empty_n,
        A_2_read,
        A_3_dout,
        A_3_num_data_valid,
        A_3_fifo_cap,
        A_3_empty_n,
        A_3_read,
        A_4_dout,
        A_4_num_data_valid,
        A_4_fifo_cap,
        A_4_empty_n,
        A_4_read,
        A_5_dout,
        A_5_num_data_valid,
        A_5_fifo_cap,
        A_5_empty_n,
        A_5_read,
        A_6_dout,
        A_6_num_data_valid,
        A_6_fifo_cap,
        A_6_empty_n,
        A_6_read,
        A_7_dout,
        A_7_num_data_valid,
        A_7_fifo_cap,
        A_7_empty_n,
        A_7_read,
        C_0_din,
        C_0_num_data_valid,
        C_0_fifo_cap,
        C_0_full_n,
        C_0_write,
        start_out,
        start_write,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] A_dout;
input  [6:0] A_num_data_valid;
input  [6:0] A_fifo_cap;
input   A_empty_n;
output   A_read;
input  [7:0] A_1_dout;
input  [6:0] A_1_num_data_valid;
input  [6:0] A_1_fifo_cap;
input   A_1_empty_n;
output   A_1_read;
input  [7:0] A_2_dout;
input  [6:0] A_2_num_data_valid;
input  [6:0] A_2_fifo_cap;
input   A_2_empty_n;
output   A_2_read;
input  [7:0] A_3_dout;
input  [6:0] A_3_num_data_valid;
input  [6:0] A_3_fifo_cap;
input   A_3_empty_n;
output   A_3_read;
input  [7:0] A_4_dout;
input  [6:0] A_4_num_data_valid;
input  [6:0] A_4_fifo_cap;
input   A_4_empty_n;
output   A_4_read;
input  [7:0] A_5_dout;
input  [6:0] A_5_num_data_valid;
input  [6:0] A_5_fifo_cap;
input   A_5_empty_n;
output   A_5_read;
input  [7:0] A_6_dout;
input  [6:0] A_6_num_data_valid;
input  [6:0] A_6_fifo_cap;
input   A_6_empty_n;
output   A_6_read;
input  [7:0] A_7_dout;
input  [6:0] A_7_num_data_valid;
input  [6:0] A_7_fifo_cap;
input   A_7_empty_n;
output   A_7_read;
output  [7:0] C_0_din;
input  [6:0] C_0_num_data_valid;
input  [6:0] C_0_fifo_cap;
input   C_0_full_n;
output   C_0_write;
output   start_out;
output   start_write;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;

reg ap_idle;
reg A_read;
reg A_1_read;
reg A_2_read;
reg A_3_read;
reg A_4_read;
reg A_5_read;
reg A_6_read;
reg A_7_read;
reg C_0_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln92_fu_195_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    A_blk_n;
wire    ap_block_pp0_stage0;
reg    A_1_blk_n;
reg    A_2_blk_n;
reg    A_3_blk_n;
reg    A_4_blk_n;
reg    A_5_blk_n;
reg    A_6_blk_n;
reg    A_7_blk_n;
reg    C_0_blk_n;
reg  signed [15:0] p_read_1_reg_324;
reg    ap_block_pp0_stage0_11001;
reg  signed [15:0] p_read_2_reg_329;
reg  signed [15:0] p_read_2_reg_329_pp0_iter1_reg;
reg  signed [15:0] p_read_2_reg_329_pp0_iter2_reg;
reg  signed [15:0] p_read_3_reg_334;
reg  signed [15:0] p_read_4_reg_339;
reg  signed [15:0] p_read_4_reg_339_pp0_iter1_reg;
reg  signed [15:0] p_read_4_reg_339_pp0_iter2_reg;
reg  signed [15:0] p_read_5_reg_344;
reg  signed [15:0] p_read_6_reg_349;
reg  signed [15:0] p_read_6_reg_349_pp0_iter1_reg;
reg  signed [15:0] p_read_6_reg_349_pp0_iter2_reg;
reg  signed [15:0] p_read_7_reg_354;
reg  signed [15:0] p_read_7_reg_354_pp0_iter1_reg;
reg  signed [15:0] p_read_7_reg_354_pp0_iter2_reg;
reg  signed [15:0] p_read_8_reg_359;
reg   [7:0] A_1_read_reg_373;
reg   [7:0] A_1_read_reg_373_pp0_iter2_reg;
reg   [7:0] A_2_read_reg_378;
reg   [7:0] A_2_read_reg_378_pp0_iter2_reg;
reg   [7:0] A_4_read_reg_388;
reg   [7:0] A_4_read_reg_388_pp0_iter2_reg;
reg   [7:0] A_6_read_reg_398;
reg   [7:0] A_6_read_reg_398_pp0_iter2_reg;
wire   [15:0] mul_ln97_fu_231_p2;
wire   [15:0] mul_ln97_1_fu_239_p2;
wire   [15:0] mul_ln97_3_fu_247_p2;
wire   [15:0] mul_ln97_5_fu_255_p2;
reg   [6:0] i_fu_80;
wire   [6:0] add_ln92_fu_201_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] mul_ln97_fu_231_p0;
wire   [7:0] mul_ln97_1_fu_239_p0;
wire   [7:0] mul_ln97_3_fu_247_p0;
wire   [7:0] mul_ln97_5_fu_255_p0;
wire  signed [15:0] add_ln97_2_fu_260_p0;
wire   [15:0] grp_fu_293_p3;
wire  signed [15:0] add_ln97_2_fu_260_p1;
wire   [15:0] grp_fu_285_p3;
wire  signed [15:0] add_ln97_5_fu_264_p0;
wire   [15:0] grp_fu_309_p3;
wire  signed [15:0] add_ln97_5_fu_264_p1;
wire   [15:0] grp_fu_301_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln97_5_fu_264_p2;
(* use_dsp48 = "no" *) wire   [15:0] add_ln97_2_fu_260_p2;
wire   [15:0] sum_1_fu_268_p2;
wire   [7:0] grp_fu_285_p0;
wire   [7:0] grp_fu_293_p0;
wire   [7:0] grp_fu_301_p0;
wire   [7:0] grp_fu_309_p0;
reg    grp_fu_285_ce;
reg    grp_fu_293_ce;
reg    grp_fu_301_ce;
reg    grp_fu_309_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_285_p00;
wire   [15:0] grp_fu_293_p00;
wire   [15:0] grp_fu_301_p00;
wire   [15:0] grp_fu_309_p00;
wire   [15:0] mul_ln97_1_fu_239_p00;
wire   [15:0] mul_ln97_3_fu_247_p00;
wire   [15:0] mul_ln97_5_fu_255_p00;
wire   [15:0] mul_ln97_fu_231_p00;
reg    ap_condition_253;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_80 = 7'd0;
end

myip_v1_0_HLS_mul_8ns_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_8ns_16s_16_1_1_U17(
    .din0(mul_ln97_fu_231_p0),
    .din1(p_read_7_reg_354_pp0_iter2_reg),
    .dout(mul_ln97_fu_231_p2)
);

myip_v1_0_HLS_mul_8ns_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_8ns_16s_16_1_1_U18(
    .din0(mul_ln97_1_fu_239_p0),
    .din1(p_read_6_reg_349_pp0_iter2_reg),
    .dout(mul_ln97_1_fu_239_p2)
);

myip_v1_0_HLS_mul_8ns_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_8ns_16s_16_1_1_U19(
    .din0(mul_ln97_3_fu_247_p0),
    .din1(p_read_4_reg_339_pp0_iter2_reg),
    .dout(mul_ln97_3_fu_247_p2)
);

myip_v1_0_HLS_mul_8ns_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_8ns_16s_16_1_1_U20(
    .din0(mul_ln97_5_fu_255_p0),
    .din1(p_read_2_reg_329_pp0_iter2_reg),
    .dout(mul_ln97_5_fu_255_p2)
);

myip_v1_0_HLS_mac_muladd_8ns_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_16s_16ns_16_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_285_p0),
    .din1(p_read_8_reg_359),
    .din2(mul_ln97_fu_231_p2),
    .ce(grp_fu_285_ce),
    .dout(grp_fu_285_p3)
);

myip_v1_0_HLS_mac_muladd_8ns_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_16s_16ns_16_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_293_p0),
    .din1(p_read_5_reg_344),
    .din2(mul_ln97_1_fu_239_p2),
    .ce(grp_fu_293_ce),
    .dout(grp_fu_293_p3)
);

myip_v1_0_HLS_mac_muladd_8ns_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_16s_16ns_16_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_301_p0),
    .din1(p_read_3_reg_334),
    .din2(mul_ln97_3_fu_247_p2),
    .ce(grp_fu_301_ce),
    .dout(grp_fu_301_p3)
);

myip_v1_0_HLS_mac_muladd_8ns_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_16s_16ns_16_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_309_p0),
    .din1(p_read_1_reg_324),
    .din2(mul_ln97_5_fu_255_p2),
    .ce(grp_fu_309_ce),
    .dout(grp_fu_309_p3)
);

myip_v1_0_HLS_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_253)) begin
        if ((icmp_ln92_fu_195_p2 == 1'd0)) begin
            i_fu_80 <= add_ln92_fu_201_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_1_read_reg_373 <= A_1_dout;
        A_2_read_reg_378 <= A_2_dout;
        A_4_read_reg_388 <= A_4_dout;
        A_6_read_reg_398 <= A_6_dout;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        p_read_1_reg_324 <= p_read7;
        p_read_2_reg_329 <= p_read6;
        p_read_2_reg_329_pp0_iter1_reg <= p_read_2_reg_329;
        p_read_3_reg_334 <= p_read5;
        p_read_4_reg_339 <= p_read4;
        p_read_4_reg_339_pp0_iter1_reg <= p_read_4_reg_339;
        p_read_5_reg_344 <= p_read3;
        p_read_6_reg_349 <= p_read2;
        p_read_6_reg_349_pp0_iter1_reg <= p_read_6_reg_349;
        p_read_7_reg_354 <= p_read1;
        p_read_7_reg_354_pp0_iter1_reg <= p_read_7_reg_354;
        p_read_8_reg_359 <= p_read;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        A_1_read_reg_373_pp0_iter2_reg <= A_1_read_reg_373;
        A_2_read_reg_378_pp0_iter2_reg <= A_2_read_reg_378;
        A_4_read_reg_388_pp0_iter2_reg <= A_4_read_reg_388;
        A_6_read_reg_398_pp0_iter2_reg <= A_6_read_reg_398;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        p_read_2_reg_329_pp0_iter2_reg <= p_read_2_reg_329_pp0_iter1_reg;
        p_read_4_reg_339_pp0_iter2_reg <= p_read_4_reg_339_pp0_iter1_reg;
        p_read_6_reg_349_pp0_iter2_reg <= p_read_6_reg_349_pp0_iter1_reg;
        p_read_7_reg_354_pp0_iter2_reg <= p_read_7_reg_354_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_1_blk_n = A_1_empty_n;
    end else begin
        A_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_1_read = 1'b1;
    end else begin
        A_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_2_blk_n = A_2_empty_n;
    end else begin
        A_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_2_read = 1'b1;
    end else begin
        A_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_3_blk_n = A_3_empty_n;
    end else begin
        A_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_3_read = 1'b1;
    end else begin
        A_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_4_blk_n = A_4_empty_n;
    end else begin
        A_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_4_read = 1'b1;
    end else begin
        A_4_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_5_blk_n = A_5_empty_n;
    end else begin
        A_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_5_read = 1'b1;
    end else begin
        A_5_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_6_blk_n = A_6_empty_n;
    end else begin
        A_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_6_read = 1'b1;
    end else begin
        A_6_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_7_blk_n = A_7_empty_n;
    end else begin
        A_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_7_read = 1'b1;
    end else begin
        A_7_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        A_blk_n = A_empty_n;
    end else begin
        A_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_read = 1'b1;
    end else begin
        A_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        C_0_blk_n = C_0_full_n;
    end else begin
        C_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        C_0_write = 1'b1;
    end else begin
        C_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln92_fu_195_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_80;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_285_ce = 1'b1;
    end else begin
        grp_fu_285_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_293_ce = 1'b1;
    end else begin
        grp_fu_293_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_301_ce = 1'b1;
    end else begin
        grp_fu_301_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_309_ce = 1'b1;
    end else begin
        grp_fu_309_ce = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_0_din = {{sum_1_fu_268_p2[15:8]}};

assign add_ln92_fu_201_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign add_ln97_2_fu_260_p0 = grp_fu_293_p3;

assign add_ln97_2_fu_260_p1 = grp_fu_285_p3;

assign add_ln97_2_fu_260_p2 = ($signed(add_ln97_2_fu_260_p0) + $signed(add_ln97_2_fu_260_p1));

assign add_ln97_5_fu_264_p0 = grp_fu_309_p3;

assign add_ln97_5_fu_264_p1 = grp_fu_301_p3;

assign add_ln97_5_fu_264_p2 = ($signed(add_ln97_5_fu_264_p0) + $signed(add_ln97_5_fu_264_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((1'b0 == A_5_empty_n) | (1'b0 == A_4_empty_n) | (1'b0 == A_3_empty_n) | (1'b0 == A_2_empty_n) | (1'b0 == A_1_empty_n) | (1'b0 == A_empty_n) | (1'b0 == A_7_empty_n) | (1'b0 == A_6_empty_n));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (1'b0 == C_0_full_n);
end

always @ (*) begin
    ap_condition_253 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign grp_fu_285_p0 = grp_fu_285_p00;

assign grp_fu_285_p00 = A_dout;

assign grp_fu_293_p0 = grp_fu_293_p00;

assign grp_fu_293_p00 = A_3_dout;

assign grp_fu_301_p0 = grp_fu_301_p00;

assign grp_fu_301_p00 = A_5_dout;

assign grp_fu_309_p0 = grp_fu_309_p00;

assign grp_fu_309_p00 = A_7_dout;

assign icmp_ln92_fu_195_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign mul_ln97_1_fu_239_p0 = mul_ln97_1_fu_239_p00;

assign mul_ln97_1_fu_239_p00 = A_2_read_reg_378_pp0_iter2_reg;

assign mul_ln97_3_fu_247_p0 = mul_ln97_3_fu_247_p00;

assign mul_ln97_3_fu_247_p00 = A_4_read_reg_388_pp0_iter2_reg;

assign mul_ln97_5_fu_255_p0 = mul_ln97_5_fu_255_p00;

assign mul_ln97_5_fu_255_p00 = A_6_read_reg_398_pp0_iter2_reg;

assign mul_ln97_fu_231_p0 = mul_ln97_fu_231_p00;

assign mul_ln97_fu_231_p00 = A_1_read_reg_373_pp0_iter2_reg;

assign start_out = real_start;

assign sum_1_fu_268_p2 = (add_ln97_5_fu_264_p2 + add_ln97_2_fu_260_p2);

endmodule //myip_v1_0_HLS_Loop_VITIS_LOOP_92_3_proc
