// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myip_v1_0_HLS_myip_v1_0_HLS,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.346000,HLS_SYN_LAT=589,HLS_SYN_TPT=520,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6447,HLS_SYN_LUT=7830,HLS_VERSION=2023_2}" *)

module myip_v1_0_HLS (
        S_AXIS_TDATA,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST,
        ap_clk,
        ap_rst_n,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        M_AXIS_TVALID,
        M_AXIS_TREADY
);


input  [31:0] S_AXIS_TDATA;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;
input   ap_clk;
input   ap_rst_n;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;

 reg    ap_rst_n_inv;
wire    Block_entry68_proc2_U0_ap_start;
wire    Block_entry68_proc2_U0_ap_done;
wire    Block_entry68_proc2_U0_ap_continue;
wire    Block_entry68_proc2_U0_ap_idle;
wire    Block_entry68_proc2_U0_ap_ready;
wire    Block_entry68_proc2_U0_S_AXIS_TREADY;
wire   [7:0] Block_entry68_proc2_U0_A_din;
wire    Block_entry68_proc2_U0_A_write;
wire   [7:0] Block_entry68_proc2_U0_A_1_din;
wire    Block_entry68_proc2_U0_A_1_write;
wire   [7:0] Block_entry68_proc2_U0_A_2_din;
wire    Block_entry68_proc2_U0_A_2_write;
wire   [7:0] Block_entry68_proc2_U0_A_3_din;
wire    Block_entry68_proc2_U0_A_3_write;
wire   [7:0] Block_entry68_proc2_U0_A_4_din;
wire    Block_entry68_proc2_U0_A_4_write;
wire   [7:0] Block_entry68_proc2_U0_A_5_din;
wire    Block_entry68_proc2_U0_A_5_write;
wire   [7:0] Block_entry68_proc2_U0_A_6_din;
wire    Block_entry68_proc2_U0_A_6_write;
wire   [7:0] Block_entry68_proc2_U0_A_7_din;
wire    Block_entry68_proc2_U0_A_7_write;
wire   [15:0] Block_entry68_proc2_U0_ap_return_0;
wire   [15:0] Block_entry68_proc2_U0_ap_return_1;
wire   [15:0] Block_entry68_proc2_U0_ap_return_2;
wire   [15:0] Block_entry68_proc2_U0_ap_return_3;
wire   [15:0] Block_entry68_proc2_U0_ap_return_4;
wire   [15:0] Block_entry68_proc2_U0_ap_return_5;
wire   [15:0] Block_entry68_proc2_U0_ap_return_6;
wire   [15:0] Block_entry68_proc2_U0_ap_return_7;
wire    ap_channel_done_conv3_i11_i_7_loc_channel;
wire    conv3_i11_i_7_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_7_loc_channel;
wire    ap_channel_done_conv3_i11_i_6_loc_channel;
wire    conv3_i11_i_6_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_6_loc_channel;
wire    ap_channel_done_conv3_i11_i_5_loc_channel;
wire    conv3_i11_i_5_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_5_loc_channel;
wire    ap_channel_done_conv3_i11_i_4_loc_channel;
wire    conv3_i11_i_4_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_4_loc_channel;
wire    ap_channel_done_conv3_i11_i_3_loc_channel;
wire    conv3_i11_i_3_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_3_loc_channel;
wire    ap_channel_done_conv3_i11_i_2_loc_channel;
wire    conv3_i11_i_2_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_2_loc_channel;
wire    ap_channel_done_conv3_i11_i_1_loc_channel;
wire    conv3_i11_i_1_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_1_loc_channel;
wire    ap_channel_done_conv3_i11_i_loc_channel;
wire    conv3_i11_i_loc_channel_full_n;
reg    ap_sync_reg_channel_write_conv3_i11_i_loc_channel;
wire    ap_sync_channel_write_conv3_i11_i_loc_channel;
wire    Loop_VITIS_LOOP_92_3_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_92_3_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_92_3_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_92_3_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_92_3_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_1_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_2_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_3_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_4_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_5_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_6_read;
wire    Loop_VITIS_LOOP_92_3_proc_U0_A_7_read;
wire   [7:0] Loop_VITIS_LOOP_92_3_proc_U0_C_0_din;
wire    Loop_VITIS_LOOP_92_3_proc_U0_C_0_write;
wire    Loop_VITIS_LOOP_92_3_proc_U0_start_out;
wire    Loop_VITIS_LOOP_92_3_proc_U0_start_write;
wire    Block_for_end52_proc3_U0_ap_start;
wire    Block_for_end52_proc3_U0_ap_done;
wire    Block_for_end52_proc3_U0_ap_continue;
wire    Block_for_end52_proc3_U0_ap_idle;
wire    Block_for_end52_proc3_U0_ap_ready;
wire    Block_for_end52_proc3_U0_C_0_read;
wire   [31:0] Block_for_end52_proc3_U0_M_AXIS_TDATA;
wire    Block_for_end52_proc3_U0_M_AXIS_TVALID;
wire   [3:0] Block_for_end52_proc3_U0_M_AXIS_TKEEP;
wire   [3:0] Block_for_end52_proc3_U0_M_AXIS_TSTRB;
wire   [0:0] Block_for_end52_proc3_U0_M_AXIS_TLAST;
wire    A_channel_full_n;
wire   [7:0] A_channel_dout;
wire   [6:0] A_channel_num_data_valid;
wire   [6:0] A_channel_fifo_cap;
wire    A_channel_empty_n;
wire    A_1_channel_full_n;
wire   [7:0] A_1_channel_dout;
wire   [6:0] A_1_channel_num_data_valid;
wire   [6:0] A_1_channel_fifo_cap;
wire    A_1_channel_empty_n;
wire    A_2_channel_full_n;
wire   [7:0] A_2_channel_dout;
wire   [6:0] A_2_channel_num_data_valid;
wire   [6:0] A_2_channel_fifo_cap;
wire    A_2_channel_empty_n;
wire    A_3_channel_full_n;
wire   [7:0] A_3_channel_dout;
wire   [6:0] A_3_channel_num_data_valid;
wire   [6:0] A_3_channel_fifo_cap;
wire    A_3_channel_empty_n;
wire    A_4_channel_full_n;
wire   [7:0] A_4_channel_dout;
wire   [6:0] A_4_channel_num_data_valid;
wire   [6:0] A_4_channel_fifo_cap;
wire    A_4_channel_empty_n;
wire    A_5_channel_full_n;
wire   [7:0] A_5_channel_dout;
wire   [6:0] A_5_channel_num_data_valid;
wire   [6:0] A_5_channel_fifo_cap;
wire    A_5_channel_empty_n;
wire    A_6_channel_full_n;
wire   [7:0] A_6_channel_dout;
wire   [6:0] A_6_channel_num_data_valid;
wire   [6:0] A_6_channel_fifo_cap;
wire    A_6_channel_empty_n;
wire    A_7_channel_full_n;
wire   [7:0] A_7_channel_dout;
wire   [6:0] A_7_channel_num_data_valid;
wire   [6:0] A_7_channel_fifo_cap;
wire    A_7_channel_empty_n;
wire   [15:0] conv3_i11_i_loc_channel_dout;
wire   [2:0] conv3_i11_i_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_loc_channel_fifo_cap;
wire    conv3_i11_i_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_1_loc_channel_dout;
wire   [2:0] conv3_i11_i_1_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_1_loc_channel_fifo_cap;
wire    conv3_i11_i_1_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_2_loc_channel_dout;
wire   [2:0] conv3_i11_i_2_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_2_loc_channel_fifo_cap;
wire    conv3_i11_i_2_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_3_loc_channel_dout;
wire   [2:0] conv3_i11_i_3_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_3_loc_channel_fifo_cap;
wire    conv3_i11_i_3_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_4_loc_channel_dout;
wire   [2:0] conv3_i11_i_4_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_4_loc_channel_fifo_cap;
wire    conv3_i11_i_4_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_5_loc_channel_dout;
wire   [2:0] conv3_i11_i_5_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_5_loc_channel_fifo_cap;
wire    conv3_i11_i_5_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_6_loc_channel_dout;
wire   [2:0] conv3_i11_i_6_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_6_loc_channel_fifo_cap;
wire    conv3_i11_i_6_loc_channel_empty_n;
wire   [15:0] conv3_i11_i_7_loc_channel_dout;
wire   [2:0] conv3_i11_i_7_loc_channel_num_data_valid;
wire   [2:0] conv3_i11_i_7_loc_channel_fifo_cap;
wire    conv3_i11_i_7_loc_channel_empty_n;
wire    C_0_full_n;
wire   [7:0] C_0_dout;
wire   [6:0] C_0_num_data_valid;
wire   [6:0] C_0_fifo_cap;
wire    C_0_empty_n;
wire   [0:0] start_for_Block_for_end52_proc3_U0_din;
wire    start_for_Block_for_end52_proc3_U0_full_n;
wire   [0:0] start_for_Block_for_end52_proc3_U0_dout;
wire    start_for_Block_for_end52_proc3_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_conv3_i11_i_loc_channel = 1'b0;
end

myip_v1_0_HLS_Block_entry68_proc2 Block_entry68_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry68_proc2_U0_ap_start),
    .ap_done(Block_entry68_proc2_U0_ap_done),
    .ap_continue(Block_entry68_proc2_U0_ap_continue),
    .ap_idle(Block_entry68_proc2_U0_ap_idle),
    .ap_ready(Block_entry68_proc2_U0_ap_ready),
    .S_AXIS_TDATA(S_AXIS_TDATA),
    .S_AXIS_TVALID(S_AXIS_TVALID),
    .S_AXIS_TREADY(Block_entry68_proc2_U0_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP),
    .S_AXIS_TSTRB(S_AXIS_TSTRB),
    .S_AXIS_TLAST(S_AXIS_TLAST),
    .A_din(Block_entry68_proc2_U0_A_din),
    .A_num_data_valid(A_channel_num_data_valid),
    .A_fifo_cap(A_channel_fifo_cap),
    .A_full_n(A_channel_full_n),
    .A_write(Block_entry68_proc2_U0_A_write),
    .A_1_din(Block_entry68_proc2_U0_A_1_din),
    .A_1_num_data_valid(A_1_channel_num_data_valid),
    .A_1_fifo_cap(A_1_channel_fifo_cap),
    .A_1_full_n(A_1_channel_full_n),
    .A_1_write(Block_entry68_proc2_U0_A_1_write),
    .A_2_din(Block_entry68_proc2_U0_A_2_din),
    .A_2_num_data_valid(A_2_channel_num_data_valid),
    .A_2_fifo_cap(A_2_channel_fifo_cap),
    .A_2_full_n(A_2_channel_full_n),
    .A_2_write(Block_entry68_proc2_U0_A_2_write),
    .A_3_din(Block_entry68_proc2_U0_A_3_din),
    .A_3_num_data_valid(A_3_channel_num_data_valid),
    .A_3_fifo_cap(A_3_channel_fifo_cap),
    .A_3_full_n(A_3_channel_full_n),
    .A_3_write(Block_entry68_proc2_U0_A_3_write),
    .A_4_din(Block_entry68_proc2_U0_A_4_din),
    .A_4_num_data_valid(A_4_channel_num_data_valid),
    .A_4_fifo_cap(A_4_channel_fifo_cap),
    .A_4_full_n(A_4_channel_full_n),
    .A_4_write(Block_entry68_proc2_U0_A_4_write),
    .A_5_din(Block_entry68_proc2_U0_A_5_din),
    .A_5_num_data_valid(A_5_channel_num_data_valid),
    .A_5_fifo_cap(A_5_channel_fifo_cap),
    .A_5_full_n(A_5_channel_full_n),
    .A_5_write(Block_entry68_proc2_U0_A_5_write),
    .A_6_din(Block_entry68_proc2_U0_A_6_din),
    .A_6_num_data_valid(A_6_channel_num_data_valid),
    .A_6_fifo_cap(A_6_channel_fifo_cap),
    .A_6_full_n(A_6_channel_full_n),
    .A_6_write(Block_entry68_proc2_U0_A_6_write),
    .A_7_din(Block_entry68_proc2_U0_A_7_din),
    .A_7_num_data_valid(A_7_channel_num_data_valid),
    .A_7_fifo_cap(A_7_channel_fifo_cap),
    .A_7_full_n(A_7_channel_full_n),
    .A_7_write(Block_entry68_proc2_U0_A_7_write),
    .ap_return_0(Block_entry68_proc2_U0_ap_return_0),
    .ap_return_1(Block_entry68_proc2_U0_ap_return_1),
    .ap_return_2(Block_entry68_proc2_U0_ap_return_2),
    .ap_return_3(Block_entry68_proc2_U0_ap_return_3),
    .ap_return_4(Block_entry68_proc2_U0_ap_return_4),
    .ap_return_5(Block_entry68_proc2_U0_ap_return_5),
    .ap_return_6(Block_entry68_proc2_U0_ap_return_6),
    .ap_return_7(Block_entry68_proc2_U0_ap_return_7)
);

myip_v1_0_HLS_Loop_VITIS_LOOP_92_3_proc Loop_VITIS_LOOP_92_3_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_92_3_proc_U0_ap_start),
    .start_full_n(start_for_Block_for_end52_proc3_U0_full_n),
    .ap_done(Loop_VITIS_LOOP_92_3_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_92_3_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_92_3_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready),
    .A_dout(A_channel_dout),
    .A_num_data_valid(A_channel_num_data_valid),
    .A_fifo_cap(A_channel_fifo_cap),
    .A_empty_n(A_channel_empty_n),
    .A_read(Loop_VITIS_LOOP_92_3_proc_U0_A_read),
    .A_1_dout(A_1_channel_dout),
    .A_1_num_data_valid(A_1_channel_num_data_valid),
    .A_1_fifo_cap(A_1_channel_fifo_cap),
    .A_1_empty_n(A_1_channel_empty_n),
    .A_1_read(Loop_VITIS_LOOP_92_3_proc_U0_A_1_read),
    .A_2_dout(A_2_channel_dout),
    .A_2_num_data_valid(A_2_channel_num_data_valid),
    .A_2_fifo_cap(A_2_channel_fifo_cap),
    .A_2_empty_n(A_2_channel_empty_n),
    .A_2_read(Loop_VITIS_LOOP_92_3_proc_U0_A_2_read),
    .A_3_dout(A_3_channel_dout),
    .A_3_num_data_valid(A_3_channel_num_data_valid),
    .A_3_fifo_cap(A_3_channel_fifo_cap),
    .A_3_empty_n(A_3_channel_empty_n),
    .A_3_read(Loop_VITIS_LOOP_92_3_proc_U0_A_3_read),
    .A_4_dout(A_4_channel_dout),
    .A_4_num_data_valid(A_4_channel_num_data_valid),
    .A_4_fifo_cap(A_4_channel_fifo_cap),
    .A_4_empty_n(A_4_channel_empty_n),
    .A_4_read(Loop_VITIS_LOOP_92_3_proc_U0_A_4_read),
    .A_5_dout(A_5_channel_dout),
    .A_5_num_data_valid(A_5_channel_num_data_valid),
    .A_5_fifo_cap(A_5_channel_fifo_cap),
    .A_5_empty_n(A_5_channel_empty_n),
    .A_5_read(Loop_VITIS_LOOP_92_3_proc_U0_A_5_read),
    .A_6_dout(A_6_channel_dout),
    .A_6_num_data_valid(A_6_channel_num_data_valid),
    .A_6_fifo_cap(A_6_channel_fifo_cap),
    .A_6_empty_n(A_6_channel_empty_n),
    .A_6_read(Loop_VITIS_LOOP_92_3_proc_U0_A_6_read),
    .A_7_dout(A_7_channel_dout),
    .A_7_num_data_valid(A_7_channel_num_data_valid),
    .A_7_fifo_cap(A_7_channel_fifo_cap),
    .A_7_empty_n(A_7_channel_empty_n),
    .A_7_read(Loop_VITIS_LOOP_92_3_proc_U0_A_7_read),
    .C_0_din(Loop_VITIS_LOOP_92_3_proc_U0_C_0_din),
    .C_0_num_data_valid(C_0_num_data_valid),
    .C_0_fifo_cap(C_0_fifo_cap),
    .C_0_full_n(C_0_full_n),
    .C_0_write(Loop_VITIS_LOOP_92_3_proc_U0_C_0_write),
    .start_out(Loop_VITIS_LOOP_92_3_proc_U0_start_out),
    .start_write(Loop_VITIS_LOOP_92_3_proc_U0_start_write),
    .p_read(conv3_i11_i_loc_channel_dout),
    .p_read1(conv3_i11_i_1_loc_channel_dout),
    .p_read2(conv3_i11_i_2_loc_channel_dout),
    .p_read3(conv3_i11_i_3_loc_channel_dout),
    .p_read4(conv3_i11_i_4_loc_channel_dout),
    .p_read5(conv3_i11_i_5_loc_channel_dout),
    .p_read6(conv3_i11_i_6_loc_channel_dout),
    .p_read7(conv3_i11_i_7_loc_channel_dout)
);

myip_v1_0_HLS_Block_for_end52_proc3 Block_for_end52_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_for_end52_proc3_U0_ap_start),
    .ap_done(Block_for_end52_proc3_U0_ap_done),
    .ap_continue(Block_for_end52_proc3_U0_ap_continue),
    .ap_idle(Block_for_end52_proc3_U0_ap_idle),
    .ap_ready(Block_for_end52_proc3_U0_ap_ready),
    .C_0_dout(C_0_dout),
    .C_0_num_data_valid(C_0_num_data_valid),
    .C_0_fifo_cap(C_0_fifo_cap),
    .C_0_empty_n(C_0_empty_n),
    .C_0_read(Block_for_end52_proc3_U0_C_0_read),
    .M_AXIS_TDATA(Block_for_end52_proc3_U0_M_AXIS_TDATA),
    .M_AXIS_TVALID(Block_for_end52_proc3_U0_M_AXIS_TVALID),
    .M_AXIS_TREADY(M_AXIS_TREADY),
    .M_AXIS_TKEEP(Block_for_end52_proc3_U0_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(Block_for_end52_proc3_U0_M_AXIS_TSTRB),
    .M_AXIS_TLAST(Block_for_end52_proc3_U0_M_AXIS_TLAST)
);

myip_v1_0_HLS_fifo_w8_d64_S A_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_din),
    .if_full_n(A_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_write),
    .if_dout(A_channel_dout),
    .if_num_data_valid(A_channel_num_data_valid),
    .if_fifo_cap(A_channel_fifo_cap),
    .if_empty_n(A_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_1_din),
    .if_full_n(A_1_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_1_write),
    .if_dout(A_1_channel_dout),
    .if_num_data_valid(A_1_channel_num_data_valid),
    .if_fifo_cap(A_1_channel_fifo_cap),
    .if_empty_n(A_1_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_1_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_2_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_2_din),
    .if_full_n(A_2_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_2_write),
    .if_dout(A_2_channel_dout),
    .if_num_data_valid(A_2_channel_num_data_valid),
    .if_fifo_cap(A_2_channel_fifo_cap),
    .if_empty_n(A_2_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_2_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_3_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_3_din),
    .if_full_n(A_3_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_3_write),
    .if_dout(A_3_channel_dout),
    .if_num_data_valid(A_3_channel_num_data_valid),
    .if_fifo_cap(A_3_channel_fifo_cap),
    .if_empty_n(A_3_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_3_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_4_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_4_din),
    .if_full_n(A_4_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_4_write),
    .if_dout(A_4_channel_dout),
    .if_num_data_valid(A_4_channel_num_data_valid),
    .if_fifo_cap(A_4_channel_fifo_cap),
    .if_empty_n(A_4_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_4_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_5_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_5_din),
    .if_full_n(A_5_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_5_write),
    .if_dout(A_5_channel_dout),
    .if_num_data_valid(A_5_channel_num_data_valid),
    .if_fifo_cap(A_5_channel_fifo_cap),
    .if_empty_n(A_5_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_5_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_6_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_6_din),
    .if_full_n(A_6_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_6_write),
    .if_dout(A_6_channel_dout),
    .if_num_data_valid(A_6_channel_num_data_valid),
    .if_fifo_cap(A_6_channel_fifo_cap),
    .if_empty_n(A_6_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_6_read)
);

myip_v1_0_HLS_fifo_w8_d64_S A_7_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_A_7_din),
    .if_full_n(A_7_channel_full_n),
    .if_write(Block_entry68_proc2_U0_A_7_write),
    .if_dout(A_7_channel_dout),
    .if_num_data_valid(A_7_channel_num_data_valid),
    .if_fifo_cap(A_7_channel_fifo_cap),
    .if_empty_n(A_7_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_A_7_read)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_0),
    .if_full_n(conv3_i11_i_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_loc_channel),
    .if_dout(conv3_i11_i_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_1_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_1),
    .if_full_n(conv3_i11_i_1_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_1_loc_channel),
    .if_dout(conv3_i11_i_1_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_1_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_1_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_1_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_2_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_2),
    .if_full_n(conv3_i11_i_2_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_2_loc_channel),
    .if_dout(conv3_i11_i_2_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_2_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_2_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_2_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_3_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_3),
    .if_full_n(conv3_i11_i_3_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_3_loc_channel),
    .if_dout(conv3_i11_i_3_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_3_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_3_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_3_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_4_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_4),
    .if_full_n(conv3_i11_i_4_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_4_loc_channel),
    .if_dout(conv3_i11_i_4_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_4_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_4_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_4_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_5_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_5),
    .if_full_n(conv3_i11_i_5_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_5_loc_channel),
    .if_dout(conv3_i11_i_5_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_5_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_5_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_5_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_6_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_6),
    .if_full_n(conv3_i11_i_6_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_6_loc_channel),
    .if_dout(conv3_i11_i_6_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_6_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_6_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_6_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w16_d2_S conv3_i11_i_7_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry68_proc2_U0_ap_return_7),
    .if_full_n(conv3_i11_i_7_loc_channel_full_n),
    .if_write(ap_channel_done_conv3_i11_i_7_loc_channel),
    .if_dout(conv3_i11_i_7_loc_channel_dout),
    .if_num_data_valid(conv3_i11_i_7_loc_channel_num_data_valid),
    .if_fifo_cap(conv3_i11_i_7_loc_channel_fifo_cap),
    .if_empty_n(conv3_i11_i_7_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_92_3_proc_U0_ap_ready)
);

myip_v1_0_HLS_fifo_w8_d64_S C_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_92_3_proc_U0_C_0_din),
    .if_full_n(C_0_full_n),
    .if_write(Loop_VITIS_LOOP_92_3_proc_U0_C_0_write),
    .if_dout(C_0_dout),
    .if_num_data_valid(C_0_num_data_valid),
    .if_fifo_cap(C_0_fifo_cap),
    .if_empty_n(C_0_empty_n),
    .if_read(Block_for_end52_proc3_U0_C_0_read)
);

myip_v1_0_HLS_start_for_Block_for_end52_proc3_U0 start_for_Block_for_end52_proc3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_for_end52_proc3_U0_din),
    .if_full_n(start_for_Block_for_end52_proc3_U0_full_n),
    .if_write(Loop_VITIS_LOOP_92_3_proc_U0_start_write),
    .if_dout(start_for_Block_for_end52_proc3_U0_dout),
    .if_empty_n(start_for_Block_for_end52_proc3_U0_empty_n),
    .if_read(Block_for_end52_proc3_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel <= ap_sync_channel_write_conv3_i11_i_1_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel <= ap_sync_channel_write_conv3_i11_i_2_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel <= ap_sync_channel_write_conv3_i11_i_3_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel <= ap_sync_channel_write_conv3_i11_i_4_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel <= ap_sync_channel_write_conv3_i11_i_5_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel <= ap_sync_channel_write_conv3_i11_i_6_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel <= ap_sync_channel_write_conv3_i11_i_7_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_conv3_i11_i_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry68_proc2_U0_ap_done & Block_entry68_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_conv3_i11_i_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_conv3_i11_i_loc_channel <= ap_sync_channel_write_conv3_i11_i_loc_channel;
        end
    end
end

assign Block_entry68_proc2_U0_ap_continue = (ap_sync_channel_write_conv3_i11_i_loc_channel & ap_sync_channel_write_conv3_i11_i_7_loc_channel & ap_sync_channel_write_conv3_i11_i_6_loc_channel & ap_sync_channel_write_conv3_i11_i_5_loc_channel & ap_sync_channel_write_conv3_i11_i_4_loc_channel & ap_sync_channel_write_conv3_i11_i_3_loc_channel & ap_sync_channel_write_conv3_i11_i_2_loc_channel & ap_sync_channel_write_conv3_i11_i_1_loc_channel);

assign Block_entry68_proc2_U0_ap_start = 1'b1;

assign Block_for_end52_proc3_U0_ap_continue = 1'b1;

assign Block_for_end52_proc3_U0_ap_start = start_for_Block_for_end52_proc3_U0_empty_n;

assign Loop_VITIS_LOOP_92_3_proc_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_92_3_proc_U0_ap_start = (conv3_i11_i_loc_channel_empty_n & conv3_i11_i_7_loc_channel_empty_n & conv3_i11_i_6_loc_channel_empty_n & conv3_i11_i_5_loc_channel_empty_n & conv3_i11_i_4_loc_channel_empty_n & conv3_i11_i_3_loc_channel_empty_n & conv3_i11_i_2_loc_channel_empty_n & conv3_i11_i_1_loc_channel_empty_n);

assign M_AXIS_TDATA = Block_for_end52_proc3_U0_M_AXIS_TDATA;

assign M_AXIS_TKEEP = Block_for_end52_proc3_U0_M_AXIS_TKEEP;

assign M_AXIS_TLAST = Block_for_end52_proc3_U0_M_AXIS_TLAST;

assign M_AXIS_TSTRB = Block_for_end52_proc3_U0_M_AXIS_TSTRB;

assign M_AXIS_TVALID = Block_for_end52_proc3_U0_M_AXIS_TVALID;

assign S_AXIS_TREADY = Block_entry68_proc2_U0_S_AXIS_TREADY;

assign ap_channel_done_conv3_i11_i_1_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_2_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_3_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_4_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_5_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_6_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_7_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

assign ap_channel_done_conv3_i11_i_loc_channel = ((ap_sync_reg_channel_write_conv3_i11_i_loc_channel ^ 1'b1) & Block_entry68_proc2_U0_ap_done);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_conv3_i11_i_1_loc_channel = ((conv3_i11_i_1_loc_channel_full_n & ap_channel_done_conv3_i11_i_1_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_1_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_2_loc_channel = ((conv3_i11_i_2_loc_channel_full_n & ap_channel_done_conv3_i11_i_2_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_2_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_3_loc_channel = ((conv3_i11_i_3_loc_channel_full_n & ap_channel_done_conv3_i11_i_3_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_3_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_4_loc_channel = ((conv3_i11_i_4_loc_channel_full_n & ap_channel_done_conv3_i11_i_4_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_4_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_5_loc_channel = ((conv3_i11_i_5_loc_channel_full_n & ap_channel_done_conv3_i11_i_5_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_5_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_6_loc_channel = ((conv3_i11_i_6_loc_channel_full_n & ap_channel_done_conv3_i11_i_6_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_6_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_7_loc_channel = ((conv3_i11_i_7_loc_channel_full_n & ap_channel_done_conv3_i11_i_7_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_7_loc_channel);

assign ap_sync_channel_write_conv3_i11_i_loc_channel = ((conv3_i11_i_loc_channel_full_n & ap_channel_done_conv3_i11_i_loc_channel) | ap_sync_reg_channel_write_conv3_i11_i_loc_channel);

assign start_for_Block_for_end52_proc3_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "myip_v1_0_HLS_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "myip_v1_0_HLS_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myip_v1_0_HLS

