// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_AXIS_TVALID,
        A_address0,
        A_ce0,
        A_we0,
        A_d0,
        A_1_address0,
        A_1_ce0,
        A_1_we0,
        A_1_d0,
        A_2_address0,
        A_2_ce0,
        A_2_we0,
        A_2_d0,
        A_3_address0,
        A_3_ce0,
        A_3_we0,
        A_3_d0,
        A_4_address0,
        A_4_ce0,
        A_4_we0,
        A_4_d0,
        A_5_address0,
        A_5_ce0,
        A_5_we0,
        A_5_d0,
        A_6_address0,
        A_6_ce0,
        A_6_we0,
        A_6_d0,
        A_7_address0,
        A_7_ce0,
        A_7_we0,
        A_7_d0,
        S_AXIS_TDATA,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        WEIGHTS_N1_VEC_HIDDEN_address0,
        WEIGHTS_N1_VEC_HIDDEN_ce0,
        WEIGHTS_N1_VEC_HIDDEN_we0,
        WEIGHTS_N1_VEC_HIDDEN_d0,
        WEIGHTS_N2_VEC_HIDDEN_address0,
        WEIGHTS_N2_VEC_HIDDEN_ce0,
        WEIGHTS_N2_VEC_HIDDEN_we0,
        WEIGHTS_N2_VEC_HIDDEN_d0,
        WEIGHTS_VEC_RES_2_018_out,
        WEIGHTS_VEC_RES_2_018_out_ap_vld,
        WEIGHTS_VEC_RES_1_017_out,
        WEIGHTS_VEC_RES_1_017_out_ap_vld,
        WEIGHTS_VEC_RES_0_016_out,
        WEIGHTS_VEC_RES_0_016_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   S_AXIS_TVALID;
output  [5:0] A_address0;
output   A_ce0;
output   A_we0;
output  [7:0] A_d0;
output  [5:0] A_1_address0;
output   A_1_ce0;
output   A_1_we0;
output  [7:0] A_1_d0;
output  [5:0] A_2_address0;
output   A_2_ce0;
output   A_2_we0;
output  [7:0] A_2_d0;
output  [5:0] A_3_address0;
output   A_3_ce0;
output   A_3_we0;
output  [7:0] A_3_d0;
output  [5:0] A_4_address0;
output   A_4_ce0;
output   A_4_we0;
output  [7:0] A_4_d0;
output  [5:0] A_5_address0;
output   A_5_ce0;
output   A_5_we0;
output  [7:0] A_5_d0;
output  [5:0] A_6_address0;
output   A_6_ce0;
output   A_6_we0;
output  [7:0] A_6_d0;
output  [5:0] A_7_address0;
output   A_7_ce0;
output   A_7_we0;
output  [7:0] A_7_d0;
input  [31:0] S_AXIS_TDATA;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [2:0] WEIGHTS_N1_VEC_HIDDEN_address0;
output   WEIGHTS_N1_VEC_HIDDEN_ce0;
output   WEIGHTS_N1_VEC_HIDDEN_we0;
output  [7:0] WEIGHTS_N1_VEC_HIDDEN_d0;
output  [2:0] WEIGHTS_N2_VEC_HIDDEN_address0;
output   WEIGHTS_N2_VEC_HIDDEN_ce0;
output   WEIGHTS_N2_VEC_HIDDEN_we0;
output  [7:0] WEIGHTS_N2_VEC_HIDDEN_d0;
output  [7:0] WEIGHTS_VEC_RES_2_018_out;
output   WEIGHTS_VEC_RES_2_018_out_ap_vld;
output  [7:0] WEIGHTS_VEC_RES_1_017_out;
output   WEIGHTS_VEC_RES_1_017_out_ap_vld;
output  [7:0] WEIGHTS_VEC_RES_0_016_out;
output   WEIGHTS_VEC_RES_0_016_out_ap_vld;

reg ap_idle;
reg A_ce0;
reg A_we0;
reg A_1_ce0;
reg A_1_we0;
reg A_2_ce0;
reg A_2_we0;
reg A_3_ce0;
reg A_3_we0;
reg A_4_ce0;
reg A_4_we0;
reg A_5_ce0;
reg A_5_we0;
reg A_6_ce0;
reg A_6_we0;
reg A_7_ce0;
reg A_7_we0;
reg S_AXIS_TREADY;
reg WEIGHTS_N1_VEC_HIDDEN_ce0;
reg WEIGHTS_N1_VEC_HIDDEN_we0;
reg WEIGHTS_N2_VEC_HIDDEN_ce0;
reg WEIGHTS_N2_VEC_HIDDEN_we0;
reg WEIGHTS_VEC_RES_2_018_out_ap_vld;
reg WEIGHTS_VEC_RES_1_017_out_ap_vld;
reg WEIGHTS_VEC_RES_0_016_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln93_fu_295_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    S_AXIS_TDATA_blk_n;
wire   [63:0] zext_ln97_fu_347_p1;
wire   [0:0] tmp_fu_315_p3;
wire   [63:0] zext_ln101_fu_390_p1;
wire   [0:0] icmp_ln98_fu_359_p2;
wire   [0:0] icmp_ln100_fu_365_p2;
wire   [63:0] zext_ln99_fu_395_p1;
reg   [9:0] word_cnt_fu_108;
wire   [9:0] add_ln93_fu_301_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_word_cnt_1;
reg   [7:0] WEIGHTS_VEC_RES_0_016_fu_112;
wire   [7:0] WEIGHTS_VEC_RES_1_fu_323_p1;
wire   [1:0] trunc_ln103_fu_371_p1;
reg   [7:0] WEIGHTS_VEC_RES_1_017_fu_116;
reg   [7:0] WEIGHTS_VEC_RES_2_018_fu_120;
wire   [2:0] trunc_ln93_fu_307_p1;
wire   [5:0] div_udiv_fu_337_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 word_cnt_fu_108 = 10'd0;
#0 WEIGHTS_VEC_RES_0_016_fu_112 = 8'd0;
#0 WEIGHTS_VEC_RES_1_017_fu_116 = 8'd0;
#0 WEIGHTS_VEC_RES_2_018_fu_120 = 8'd0;
#0 ap_done_reg = 1'b0;
end

mlp_nn_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln93_fu_295_p2 == 1'd0)) begin
            word_cnt_fu_108 <= add_ln93_fu_301_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            word_cnt_fu_108 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln103_fu_371_p1 == 2'd0) & (icmp_ln100_fu_365_p2 == 1'd0) & (icmp_ln98_fu_359_p2 == 1'd0) & (tmp_fu_315_p3 == 1'd1))) begin
        WEIGHTS_VEC_RES_0_016_fu_112 <= WEIGHTS_VEC_RES_1_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln103_fu_371_p1 == 2'd1) & (icmp_ln100_fu_365_p2 == 1'd0) & (icmp_ln98_fu_359_p2 == 1'd0) & (tmp_fu_315_p3 == 1'd1))) begin
        WEIGHTS_VEC_RES_1_017_fu_116 <= WEIGHTS_VEC_RES_1_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln103_fu_371_p1 == 2'd1) & ~(trunc_ln103_fu_371_p1 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln100_fu_365_p2 == 1'd0) & (icmp_ln98_fu_359_p2 == 1'd0) & (tmp_fu_315_p3 == 1'd1))) begin
        WEIGHTS_VEC_RES_2_018_fu_120 <= WEIGHTS_VEC_RES_1_fu_323_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd1) & (tmp_fu_315_p3 == 1'd0))) begin
        A_1_we0 = 1'b1;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_2_ce0 = 1'b1;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd2) & (tmp_fu_315_p3 == 1'd0))) begin
        A_2_we0 = 1'b1;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_3_ce0 = 1'b1;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd3) & (tmp_fu_315_p3 == 1'd0))) begin
        A_3_we0 = 1'b1;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_4_ce0 = 1'b1;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd4) & (tmp_fu_315_p3 == 1'd0))) begin
        A_4_we0 = 1'b1;
    end else begin
        A_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_5_ce0 = 1'b1;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd5) & (tmp_fu_315_p3 == 1'd0))) begin
        A_5_we0 = 1'b1;
    end else begin
        A_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_6_ce0 = 1'b1;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd6) & (tmp_fu_315_p3 == 1'd0))) begin
        A_6_we0 = 1'b1;
    end else begin
        A_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_7_ce0 = 1'b1;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd7) & (tmp_fu_315_p3 == 1'd0))) begin
        A_7_we0 = 1'b1;
    end else begin
        A_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln93_fu_307_p1 == 3'd0) & (tmp_fu_315_p3 == 1'd0))) begin
        A_we0 = 1'b1;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        S_AXIS_TDATA_blk_n = S_AXIS_TVALID;
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        S_AXIS_TREADY = 1'b1;
    end else begin
        S_AXIS_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        WEIGHTS_N1_VEC_HIDDEN_ce0 = 1'b1;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln98_fu_359_p2 == 1'd1) & (tmp_fu_315_p3 == 1'd1))) begin
        WEIGHTS_N1_VEC_HIDDEN_we0 = 1'b1;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        WEIGHTS_N2_VEC_HIDDEN_ce0 = 1'b1;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln100_fu_365_p2 == 1'd1) & (icmp_ln98_fu_359_p2 == 1'd0) & (tmp_fu_315_p3 == 1'd1))) begin
        WEIGHTS_N2_VEC_HIDDEN_we0 = 1'b1;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        WEIGHTS_VEC_RES_0_016_out_ap_vld = 1'b1;
    end else begin
        WEIGHTS_VEC_RES_0_016_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        WEIGHTS_VEC_RES_1_017_out_ap_vld = 1'b1;
    end else begin
        WEIGHTS_VEC_RES_1_017_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        WEIGHTS_VEC_RES_2_018_out_ap_vld = 1'b1;
    end else begin
        WEIGHTS_VEC_RES_2_018_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln93_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_word_cnt_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_word_cnt_1 = word_cnt_fu_108;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_1_address0 = zext_ln97_fu_347_p1;

assign A_1_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_2_address0 = zext_ln97_fu_347_p1;

assign A_2_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_3_address0 = zext_ln97_fu_347_p1;

assign A_3_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_4_address0 = zext_ln97_fu_347_p1;

assign A_4_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_5_address0 = zext_ln97_fu_347_p1;

assign A_5_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_6_address0 = zext_ln97_fu_347_p1;

assign A_6_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_7_address0 = zext_ln97_fu_347_p1;

assign A_7_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign A_address0 = zext_ln97_fu_347_p1;

assign A_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign WEIGHTS_N1_VEC_HIDDEN_address0 = zext_ln99_fu_395_p1;

assign WEIGHTS_N1_VEC_HIDDEN_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign WEIGHTS_N2_VEC_HIDDEN_address0 = zext_ln101_fu_390_p1;

assign WEIGHTS_N2_VEC_HIDDEN_d0 = WEIGHTS_VEC_RES_1_fu_323_p1;

assign WEIGHTS_VEC_RES_0_016_out = WEIGHTS_VEC_RES_0_016_fu_112;

assign WEIGHTS_VEC_RES_1_017_out = WEIGHTS_VEC_RES_1_017_fu_116;

assign WEIGHTS_VEC_RES_1_fu_323_p1 = S_AXIS_TDATA[7:0];

assign WEIGHTS_VEC_RES_2_018_out = WEIGHTS_VEC_RES_2_018_fu_120;

assign add_ln93_fu_301_p2 = (ap_sig_allocacmp_word_cnt_1 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((1'b0 == S_AXIS_TVALID) & (icmp_ln93_fu_295_p2 == 1'd0)));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign div_udiv_fu_337_p4 = {{ap_sig_allocacmp_word_cnt_1[8:3]}};

assign icmp_ln100_fu_365_p2 = ((ap_sig_allocacmp_word_cnt_1 < 10'd528) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_295_p2 = ((ap_sig_allocacmp_word_cnt_1 == 10'd531) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_359_p2 = ((ap_sig_allocacmp_word_cnt_1 < 10'd520) ? 1'b1 : 1'b0);

assign tmp_fu_315_p3 = ap_sig_allocacmp_word_cnt_1[32'd9];

assign trunc_ln103_fu_371_p1 = ap_sig_allocacmp_word_cnt_1[1:0];

assign trunc_ln93_fu_307_p1 = ap_sig_allocacmp_word_cnt_1[2:0];

assign zext_ln101_fu_390_p1 = trunc_ln93_fu_307_p1;

assign zext_ln97_fu_347_p1 = div_udiv_fu_337_p4;

assign zext_ln99_fu_395_p1 = trunc_ln93_fu_307_p1;

endmodule //mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1
