// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp_nn_HLS_mlp_nn_HLS,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.187000,HLS_SYN_LAT=824,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=743,HLS_SYN_LUT=1876,HLS_VERSION=2023_2}" *)

module mlp_nn_HLS (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
reg   [7:0] ACTIVATION_FUNC_LUT_VEC_address0;
reg    ACTIVATION_FUNC_LUT_VEC_ce0;
wire   [7:0] ACTIVATION_FUNC_LUT_VEC_q0;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
wire   [7:0] WEIGHTS_N1_VEC_HIDDEN_q1;
reg   [7:0] B_load_reg_446;
wire    ap_CS_fsm_state5;
wire   [7:0] WEIGHTS_N1_VEC_HIDDEN_q0;
reg   [7:0] B_load_1_reg_451;
reg   [7:0] B_load_2_reg_466;
wire    ap_CS_fsm_state6;
reg   [7:0] B_load_3_reg_471;
reg   [7:0] B_load_4_reg_496;
wire    ap_CS_fsm_state7;
reg   [7:0] B_load_5_reg_501;
wire   [7:0] WEIGHTS_N2_VEC_HIDDEN_q1;
reg   [7:0] B_1_load_reg_516;
wire   [7:0] WEIGHTS_N2_VEC_HIDDEN_q0;
reg   [7:0] B_1_load_1_reg_521;
reg   [7:0] B_load_6_reg_536;
wire    ap_CS_fsm_state8;
reg   [7:0] B_load_7_reg_541;
reg   [7:0] B_1_load_2_reg_546;
reg   [7:0] B_1_load_3_reg_551;
reg   [7:0] B_1_load_4_reg_566;
wire    ap_CS_fsm_state9;
reg   [7:0] B_1_load_5_reg_571;
reg   [7:0] B_1_load_6_reg_586;
wire    ap_CS_fsm_state10;
reg   [7:0] B_1_load_7_reg_591;
wire   [15:0] sub_ln57_fu_411_p2;
reg   [15:0] sub_ln57_reg_602;
wire    ap_CS_fsm_state12;
reg   [5:0] A_address0;
reg    A_ce0;
reg    A_we0;
wire   [7:0] A_q0;
reg   [5:0] A_1_address0;
reg    A_1_ce0;
reg    A_1_we0;
wire   [7:0] A_1_q0;
reg   [5:0] A_2_address0;
reg    A_2_ce0;
reg    A_2_we0;
wire   [7:0] A_2_q0;
reg   [5:0] A_3_address0;
reg    A_3_ce0;
reg    A_3_we0;
wire   [7:0] A_3_q0;
reg   [5:0] A_4_address0;
reg    A_4_ce0;
reg    A_4_we0;
wire   [7:0] A_4_q0;
reg   [5:0] A_5_address0;
reg    A_5_ce0;
reg    A_5_we0;
wire   [7:0] A_5_q0;
reg   [5:0] A_6_address0;
reg    A_6_ce0;
reg    A_6_we0;
wire   [7:0] A_6_q0;
reg   [5:0] A_7_address0;
reg    A_7_ce0;
reg    A_7_we0;
wire   [7:0] A_7_q0;
reg   [5:0] N_1_address0;
reg    N_1_ce0;
reg    N_1_we0;
wire   [7:0] N_1_q0;
reg   [5:0] N_2_address0;
reg    N_2_ce0;
reg    N_2_we0;
wire   [7:0] N_2_q0;
reg   [2:0] WEIGHTS_N1_VEC_HIDDEN_address0;
reg    WEIGHTS_N1_VEC_HIDDEN_ce0;
reg    WEIGHTS_N1_VEC_HIDDEN_we0;
reg   [2:0] WEIGHTS_N1_VEC_HIDDEN_address1;
reg    WEIGHTS_N1_VEC_HIDDEN_ce1;
reg   [2:0] WEIGHTS_N2_VEC_HIDDEN_address0;
reg    WEIGHTS_N2_VEC_HIDDEN_ce0;
reg    WEIGHTS_N2_VEC_HIDDEN_we0;
reg   [2:0] WEIGHTS_N2_VEC_HIDDEN_address1;
reg    WEIGHTS_N2_VEC_HIDDEN_ce1;
reg   [5:0] RES_address0;
reg    RES_ce0;
reg    RES_we0;
wire   [7:0] RES_q0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_idle;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_ready;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_d0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_d0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_S_AXIS_TREADY;
wire   [2:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_d0;
wire   [2:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_d0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_2_018_out;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_2_018_out_ap_vld;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_1_017_out;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_1_017_out_ap_vld;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_0_016_out;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_0_016_out_ap_vld;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_done;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_idle;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_ready;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_1_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_1_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_2_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_2_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_3_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_3_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_4_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_4_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_5_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_5_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_6_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_6_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_7_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_7_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_d0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ACTIVATION_FUNC_LUT_VEC_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ACTIVATION_FUNC_LUT_VEC_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_done;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_idle;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_ready;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_1_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_1_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_2_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_2_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_3_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_3_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_4_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_4_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_5_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_5_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_6_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_6_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_7_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_7_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_d0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ACTIVATION_FUNC_LUT_VEC_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ACTIVATION_FUNC_LUT_VEC_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_done;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_idle;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_ready;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_1_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_1_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_2_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_2_ce0;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_ce0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_we0;
wire   [7:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_d0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_done;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_idle;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_ready;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TREADY;
wire   [5:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_RES_address0;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_RES_ce0;
wire   [31:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TDATA;
wire    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID;
wire   [3:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TKEEP;
wire   [3:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TSTRB;
wire   [0:0] grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TLAST;
reg    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start_reg;
reg    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start_reg;
wire    ap_CS_fsm_state13;
reg    grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire   [15:0] shl_ln_fu_403_p3;
wire   [15:0] zext_ln57_fu_399_p1;
reg   [15:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state16;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
wire    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg = 1'b0;
#0 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start_reg = 1'b0;
#0 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start_reg = 1'b0;
#0 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start_reg = 1'b0;
#0 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start_reg = 1'b0;
end

mlp_nn_HLS_ACTIVATION_FUNC_LUT_VEC_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
ACTIVATION_FUNC_LUT_VEC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ACTIVATION_FUNC_LUT_VEC_address0),
    .ce0(ACTIVATION_FUNC_LUT_VEC_ce0),
    .q0(ACTIVATION_FUNC_LUT_VEC_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_address0),
    .ce0(A_ce0),
    .we0(A_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_d0),
    .q0(A_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_1_address0),
    .ce0(A_1_ce0),
    .we0(A_1_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_d0),
    .q0(A_1_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_2_address0),
    .ce0(A_2_ce0),
    .we0(A_2_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_d0),
    .q0(A_2_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_3_address0),
    .ce0(A_3_ce0),
    .we0(A_3_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_d0),
    .q0(A_3_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_4_address0),
    .ce0(A_4_ce0),
    .we0(A_4_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_d0),
    .q0(A_4_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_5_address0),
    .ce0(A_5_ce0),
    .we0(A_5_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_d0),
    .q0(A_5_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_6_address0),
    .ce0(A_6_ce0),
    .we0(A_6_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_d0),
    .q0(A_6_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_7_address0),
    .ce0(A_7_ce0),
    .we0(A_7_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_d0),
    .q0(A_7_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
N_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(N_1_address0),
    .ce0(N_1_ce0),
    .we0(N_1_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_d0),
    .q0(N_1_q0)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
N_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(N_2_address0),
    .ce0(N_2_ce0),
    .we0(N_2_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_d0),
    .q0(N_2_q0)
);

mlp_nn_HLS_WEIGHTS_N1_VEC_HIDDEN_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
WEIGHTS_N1_VEC_HIDDEN_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(WEIGHTS_N1_VEC_HIDDEN_address0),
    .ce0(WEIGHTS_N1_VEC_HIDDEN_ce0),
    .we0(WEIGHTS_N1_VEC_HIDDEN_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_d0),
    .q0(WEIGHTS_N1_VEC_HIDDEN_q0),
    .address1(WEIGHTS_N1_VEC_HIDDEN_address1),
    .ce1(WEIGHTS_N1_VEC_HIDDEN_ce1),
    .q1(WEIGHTS_N1_VEC_HIDDEN_q1)
);

mlp_nn_HLS_WEIGHTS_N1_VEC_HIDDEN_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
WEIGHTS_N2_VEC_HIDDEN_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(WEIGHTS_N2_VEC_HIDDEN_address0),
    .ce0(WEIGHTS_N2_VEC_HIDDEN_ce0),
    .we0(WEIGHTS_N2_VEC_HIDDEN_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_d0),
    .q0(WEIGHTS_N2_VEC_HIDDEN_q0),
    .address1(WEIGHTS_N2_VEC_HIDDEN_address1),
    .ce1(WEIGHTS_N2_VEC_HIDDEN_ce1),
    .q1(WEIGHTS_N2_VEC_HIDDEN_q1)
);

mlp_nn_HLS_A_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
RES_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(RES_address0),
    .ce0(RES_ce0),
    .we0(RES_we0),
    .d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_d0),
    .q0(RES_q0)
);

mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start),
    .ap_done(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done),
    .ap_idle(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_idle),
    .ap_ready(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .A_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_address0),
    .A_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_ce0),
    .A_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_we0),
    .A_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_d0),
    .A_1_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_address0),
    .A_1_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_ce0),
    .A_1_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_we0),
    .A_1_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_d0),
    .A_2_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_address0),
    .A_2_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_ce0),
    .A_2_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_we0),
    .A_2_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_d0),
    .A_3_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_address0),
    .A_3_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_ce0),
    .A_3_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_we0),
    .A_3_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_d0),
    .A_4_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_address0),
    .A_4_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_ce0),
    .A_4_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_we0),
    .A_4_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_d0),
    .A_5_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_address0),
    .A_5_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_ce0),
    .A_5_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_we0),
    .A_5_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_d0),
    .A_6_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_address0),
    .A_6_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_ce0),
    .A_6_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_we0),
    .A_6_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_d0),
    .A_7_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_address0),
    .A_7_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_ce0),
    .A_7_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_we0),
    .A_7_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice),
    .WEIGHTS_N1_VEC_HIDDEN_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_address0),
    .WEIGHTS_N1_VEC_HIDDEN_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_ce0),
    .WEIGHTS_N1_VEC_HIDDEN_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_we0),
    .WEIGHTS_N1_VEC_HIDDEN_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_d0),
    .WEIGHTS_N2_VEC_HIDDEN_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_address0),
    .WEIGHTS_N2_VEC_HIDDEN_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_ce0),
    .WEIGHTS_N2_VEC_HIDDEN_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_we0),
    .WEIGHTS_N2_VEC_HIDDEN_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_d0),
    .WEIGHTS_VEC_RES_2_018_out(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_2_018_out),
    .WEIGHTS_VEC_RES_2_018_out_ap_vld(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_2_018_out_ap_vld),
    .WEIGHTS_VEC_RES_1_017_out(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_1_017_out),
    .WEIGHTS_VEC_RES_1_017_out_ap_vld(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_1_017_out_ap_vld),
    .WEIGHTS_VEC_RES_0_016_out(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_0_016_out),
    .WEIGHTS_VEC_RES_0_016_out_ap_vld(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_0_016_out_ap_vld)
);

mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start),
    .ap_done(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_done),
    .ap_idle(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_idle),
    .ap_ready(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_ready),
    .A_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_address0),
    .A_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_ce0),
    .A_q0(A_q0),
    .A_1_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_1_address0),
    .A_1_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_2_address0),
    .A_2_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_3_address0),
    .A_3_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_3_ce0),
    .A_3_q0(A_3_q0),
    .A_4_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_4_address0),
    .A_4_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_4_ce0),
    .A_4_q0(A_4_q0),
    .A_5_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_5_address0),
    .A_5_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_5_ce0),
    .A_5_q0(A_5_q0),
    .A_6_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_6_address0),
    .A_6_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_6_ce0),
    .A_6_q0(A_6_q0),
    .A_7_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_7_address0),
    .A_7_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_7_ce0),
    .A_7_q0(A_7_q0),
    .conv3_i11_i_i660(B_load_reg_446),
    .conv3_i11_i_i660_1(B_load_1_reg_451),
    .conv3_i11_i_i660_2(B_load_2_reg_466),
    .conv3_i11_i_i660_3(B_load_3_reg_471),
    .conv3_i11_i_i660_4(B_load_4_reg_496),
    .conv3_i11_i_i660_5(B_load_5_reg_501),
    .conv3_i11_i_i660_6(B_load_6_reg_536),
    .conv3_i11_i_i660_7(B_load_7_reg_541),
    .N_1_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_address0),
    .N_1_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_ce0),
    .N_1_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_we0),
    .N_1_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_d0),
    .ACTIVATION_FUNC_LUT_VEC_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ACTIVATION_FUNC_LUT_VEC_address0),
    .ACTIVATION_FUNC_LUT_VEC_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ACTIVATION_FUNC_LUT_VEC_ce0),
    .ACTIVATION_FUNC_LUT_VEC_q0(ACTIVATION_FUNC_LUT_VEC_q0)
);

mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start),
    .ap_done(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_done),
    .ap_idle(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_idle),
    .ap_ready(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_ready),
    .A_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_address0),
    .A_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_ce0),
    .A_q0(A_q0),
    .A_1_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_1_address0),
    .A_1_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_2_address0),
    .A_2_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_3_address0),
    .A_3_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_3_ce0),
    .A_3_q0(A_3_q0),
    .A_4_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_4_address0),
    .A_4_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_4_ce0),
    .A_4_q0(A_4_q0),
    .A_5_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_5_address0),
    .A_5_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_5_ce0),
    .A_5_q0(A_5_q0),
    .A_6_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_6_address0),
    .A_6_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_6_ce0),
    .A_6_q0(A_6_q0),
    .A_7_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_7_address0),
    .A_7_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_7_ce0),
    .A_7_q0(A_7_q0),
    .conv3_i11_i_i546(B_1_load_reg_516),
    .conv3_i11_i_i546_1(B_1_load_1_reg_521),
    .conv3_i11_i_i546_2(B_1_load_2_reg_546),
    .conv3_i11_i_i546_3(B_1_load_3_reg_551),
    .conv3_i11_i_i546_4(B_1_load_4_reg_566),
    .conv3_i11_i_i546_5(B_1_load_5_reg_571),
    .conv3_i11_i_i546_6(B_1_load_6_reg_586),
    .conv3_i11_i_i546_7(B_1_load_7_reg_591),
    .N_2_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_address0),
    .N_2_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_ce0),
    .N_2_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_we0),
    .N_2_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_d0),
    .ACTIVATION_FUNC_LUT_VEC_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ACTIVATION_FUNC_LUT_VEC_address0),
    .ACTIVATION_FUNC_LUT_VEC_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ACTIVATION_FUNC_LUT_VEC_ce0),
    .ACTIVATION_FUNC_LUT_VEC_q0(ACTIVATION_FUNC_LUT_VEC_q0)
);

mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start),
    .ap_done(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_done),
    .ap_idle(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_idle),
    .ap_ready(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_ready),
    .N_1_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_1_address0),
    .N_1_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_1_ce0),
    .N_1_q0(N_1_q0),
    .conv3_i11_i115_i(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_1_017_out),
    .N_2_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_2_address0),
    .N_2_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_2_ce0),
    .N_2_q0(N_2_q0),
    .conv3_i11_i71_i(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_2_018_out),
    .sub_ln57(sub_ln57_reg_602),
    .RES_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_address0),
    .RES_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_ce0),
    .RES_we0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_we0),
    .RES_d0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_d0)
);

mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2 grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start),
    .ap_done(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_done),
    .ap_idle(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_idle),
    .ap_ready(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_ready),
    .M_AXIS_TREADY(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TREADY),
    .RES_address0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_RES_address0),
    .RES_ce0(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_RES_ce0),
    .RES_q0(RES_q0),
    .M_AXIS_TDATA(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TDATA),
    .M_AXIS_TVALID(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID),
    .M_AXIS_TKEEP(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TSTRB),
    .M_AXIS_TLAST(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TLAST)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TDATA),
    .vld_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TKEEP),
    .vld_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TSTRB),
    .vld_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

mlp_nn_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TLAST),
    .vld_in(grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_ready == 1'b1)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_ready == 1'b1)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_ready == 1'b1)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_ready == 1'b1)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_ready == 1'b1)) begin
            grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        B_1_load_1_reg_521 <= WEIGHTS_N2_VEC_HIDDEN_q0;
        B_1_load_reg_516 <= WEIGHTS_N2_VEC_HIDDEN_q1;
        B_load_4_reg_496 <= WEIGHTS_N1_VEC_HIDDEN_q1;
        B_load_5_reg_501 <= WEIGHTS_N1_VEC_HIDDEN_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        B_1_load_2_reg_546 <= WEIGHTS_N2_VEC_HIDDEN_q1;
        B_1_load_3_reg_551 <= WEIGHTS_N2_VEC_HIDDEN_q0;
        B_load_6_reg_536 <= WEIGHTS_N1_VEC_HIDDEN_q1;
        B_load_7_reg_541 <= WEIGHTS_N1_VEC_HIDDEN_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        B_1_load_4_reg_566 <= WEIGHTS_N2_VEC_HIDDEN_q1;
        B_1_load_5_reg_571 <= WEIGHTS_N2_VEC_HIDDEN_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        B_1_load_6_reg_586 <= WEIGHTS_N2_VEC_HIDDEN_q1;
        B_1_load_7_reg_591 <= WEIGHTS_N2_VEC_HIDDEN_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_load_1_reg_451 <= WEIGHTS_N1_VEC_HIDDEN_q0;
        B_load_reg_446 <= WEIGHTS_N1_VEC_HIDDEN_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_load_2_reg_466 <= WEIGHTS_N1_VEC_HIDDEN_q1;
        B_load_3_reg_471 <= WEIGHTS_N1_VEC_HIDDEN_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        sub_ln57_reg_602 <= sub_ln57_fu_411_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ACTIVATION_FUNC_LUT_VEC_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ACTIVATION_FUNC_LUT_VEC_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        ACTIVATION_FUNC_LUT_VEC_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ACTIVATION_FUNC_LUT_VEC_address0;
    end else begin
        ACTIVATION_FUNC_LUT_VEC_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ACTIVATION_FUNC_LUT_VEC_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ACTIVATION_FUNC_LUT_VEC_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        ACTIVATION_FUNC_LUT_VEC_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ACTIVATION_FUNC_LUT_VEC_ce0;
    end else begin
        ACTIVATION_FUNC_LUT_VEC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_1_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_1_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_1_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_address0;
    end else begin
        A_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_1_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_1_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_1_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_ce0;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_1_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_1_we0;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_2_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_2_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_2_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_address0;
    end else begin
        A_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_2_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_2_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_2_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_ce0;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_2_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_2_we0;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_3_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_3_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_3_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_address0;
    end else begin
        A_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_3_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_3_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_3_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_ce0;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_3_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_3_we0;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_4_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_4_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_4_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_address0;
    end else begin
        A_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_4_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_4_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_4_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_ce0;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_4_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_4_we0;
    end else begin
        A_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_5_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_5_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_5_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_address0;
    end else begin
        A_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_5_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_5_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_5_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_ce0;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_5_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_5_we0;
    end else begin
        A_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_6_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_6_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_6_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_address0;
    end else begin
        A_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_6_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_6_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_6_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_ce0;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_6_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_6_we0;
    end else begin
        A_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_7_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_7_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_7_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_address0;
    end else begin
        A_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_7_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_7_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_7_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_ce0;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_7_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_7_we0;
    end else begin
        A_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        A_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_A_we0;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        N_1_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        N_1_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_address0;
    end else begin
        N_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        N_1_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        N_1_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_ce0;
    end else begin
        N_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        N_1_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_N_1_we0;
    end else begin
        N_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        N_2_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        N_2_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_address0;
    end else begin
        N_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        N_2_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_N_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        N_2_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_ce0;
    end else begin
        N_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        N_2_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_N_2_we0;
    end else begin
        N_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        RES_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_RES_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        RES_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_address0;
    end else begin
        RES_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        RES_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_RES_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        RES_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_ce0;
    end else begin
        RES_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        RES_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_RES_we0;
    end else begin
        RES_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        S_AXIS_TREADY_int_regslice = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_S_AXIS_TREADY;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        WEIGHTS_N1_VEC_HIDDEN_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        WEIGHTS_N1_VEC_HIDDEN_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        WEIGHTS_N1_VEC_HIDDEN_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        WEIGHTS_N1_VEC_HIDDEN_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        WEIGHTS_N1_VEC_HIDDEN_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_address0;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        WEIGHTS_N1_VEC_HIDDEN_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        WEIGHTS_N1_VEC_HIDDEN_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        WEIGHTS_N1_VEC_HIDDEN_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        WEIGHTS_N1_VEC_HIDDEN_address1 = 64'd0;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        WEIGHTS_N1_VEC_HIDDEN_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        WEIGHTS_N1_VEC_HIDDEN_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_ce0;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        WEIGHTS_N1_VEC_HIDDEN_ce1 = 1'b1;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        WEIGHTS_N1_VEC_HIDDEN_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N1_VEC_HIDDEN_we0;
    end else begin
        WEIGHTS_N1_VEC_HIDDEN_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        WEIGHTS_N2_VEC_HIDDEN_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        WEIGHTS_N2_VEC_HIDDEN_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        WEIGHTS_N2_VEC_HIDDEN_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        WEIGHTS_N2_VEC_HIDDEN_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        WEIGHTS_N2_VEC_HIDDEN_address0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_address0;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        WEIGHTS_N2_VEC_HIDDEN_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        WEIGHTS_N2_VEC_HIDDEN_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        WEIGHTS_N2_VEC_HIDDEN_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        WEIGHTS_N2_VEC_HIDDEN_address1 = 64'd0;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8) | ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        WEIGHTS_N2_VEC_HIDDEN_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        WEIGHTS_N2_VEC_HIDDEN_ce0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_ce0;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8) | ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        WEIGHTS_N2_VEC_HIDDEN_ce1 = 1'b1;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        WEIGHTS_N2_VEC_HIDDEN_we0 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_N2_VEC_HIDDEN_we0;
    end else begin
        WEIGHTS_N2_VEC_HIDDEN_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign M_AXIS_TVALID_int_regslice = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TVALID;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_M_AXIS_TREADY = (ap_CS_fsm_state15 & M_AXIS_TREADY_int_regslice);

assign grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_114_2_fu_375_ap_start_reg;

assign grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11_fu_340_ap_start_reg;

assign grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_1_fu_315_ap_start_reg;

assign grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1_fu_365_ap_start_reg;

assign grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg;

assign shl_ln_fu_403_p3 = {{grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_0_016_out}, {8'd0}};

assign sub_ln57_fu_411_p2 = (shl_ln_fu_403_p3 - zext_ln57_fu_399_p1);

assign zext_ln57_fu_399_p1 = grp_mlp_nn_HLS_Pipeline_VITIS_LOOP_93_1_fu_290_WEIGHTS_VEC_RES_0_016_out;


reg find_kernel_block = 0;
// synthesis translate_off
`include "mlp_nn_HLS_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //mlp_nn_HLS

