// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        N_1_address0,
        N_1_ce0,
        N_1_q0,
        conv3_i11_i115_i,
        N_2_address0,
        N_2_ce0,
        N_2_q0,
        conv3_i11_i71_i,
        sub_ln57,
        RES_address0,
        RES_ce0,
        RES_we0,
        RES_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] N_1_address0;
output   N_1_ce0;
input  [7:0] N_1_q0;
input  [7:0] conv3_i11_i115_i;
output  [5:0] N_2_address0;
output   N_2_ce0;
input  [7:0] N_2_q0;
input  [7:0] conv3_i11_i71_i;
input  [15:0] sub_ln57;
output  [5:0] RES_address0;
output   RES_ce0;
output   RES_we0;
output  [7:0] RES_d0;

reg ap_idle;
reg N_1_ce0;
reg N_2_ce0;
reg RES_ce0;
reg RES_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_129_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] conv3_i11_i71_i_cast_fu_113_p1;
reg   [15:0] conv3_i11_i71_i_cast_reg_213;
wire   [15:0] conv3_i11_i115_i_cast_fu_117_p1;
reg   [15:0] conv3_i11_i115_i_cast_reg_218;
wire   [63:0] zext_ln55_fu_141_p1;
reg   [63:0] zext_ln55_reg_227;
reg   [63:0] zext_ln55_reg_227_pp0_iter1_reg;
reg   [63:0] zext_ln55_reg_227_pp0_iter2_reg;
reg   [63:0] zext_ln55_reg_227_pp0_iter3_reg;
reg   [63:0] zext_ln55_reg_227_pp0_iter4_reg;
wire   [15:0] grp_fu_186_p3;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_52;
wire   [6:0] add_ln55_fu_135_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
wire   [15:0] grp_fu_192_p3;
wire   [0:0] round_up_fu_159_p3;
wire   [7:0] trunc_ln3_fu_170_p4;
wire   [7:0] zext_ln58_fu_166_p1;
wire   [7:0] grp_fu_186_p0;
wire   [7:0] grp_fu_186_p1;
wire   [7:0] grp_fu_192_p0;
wire   [7:0] grp_fu_192_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_186_p00;
wire   [15:0] grp_fu_192_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 i_fu_52 = 7'd0;
#0 ap_done_reg = 1'b0;
end

mlp_nn_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_186_p0),
    .din1(grp_fu_186_p1),
    .din2(sub_ln57),
    .ce(1'b1),
    .dout(grp_fu_186_p3)
);

mlp_nn_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_192_p0),
    .din1(grp_fu_192_p1),
    .din2(grp_fu_186_p3),
    .ce(1'b1),
    .dout(grp_fu_192_p3)
);

mlp_nn_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln55_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_52 <= add_ln55_fu_135_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_52 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv3_i11_i115_i_cast_reg_218[7 : 0] <= conv3_i11_i115_i_cast_fu_117_p1[7 : 0];
        conv3_i11_i71_i_cast_reg_213[7 : 0] <= conv3_i11_i71_i_cast_fu_113_p1[7 : 0];
        zext_ln55_reg_227[6 : 0] <= zext_ln55_fu_141_p1[6 : 0];
        zext_ln55_reg_227_pp0_iter1_reg[6 : 0] <= zext_ln55_reg_227[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        zext_ln55_reg_227_pp0_iter2_reg[6 : 0] <= zext_ln55_reg_227_pp0_iter1_reg[6 : 0];
        zext_ln55_reg_227_pp0_iter3_reg[6 : 0] <= zext_ln55_reg_227_pp0_iter2_reg[6 : 0];
        zext_ln55_reg_227_pp0_iter4_reg[6 : 0] <= zext_ln55_reg_227_pp0_iter3_reg[6 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        N_1_ce0 = 1'b1;
    end else begin
        N_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        N_2_ce0 = 1'b1;
    end else begin
        N_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        RES_ce0 = 1'b1;
    end else begin
        RES_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        RES_we0 = 1'b1;
    end else begin
        RES_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_129_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_52;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign N_1_address0 = zext_ln55_reg_227;

assign N_2_address0 = zext_ln55_fu_141_p1;

assign RES_address0 = zext_ln55_reg_227_pp0_iter4_reg;

assign RES_d0 = (trunc_ln3_fu_170_p4 + zext_ln58_fu_166_p1);

assign add_ln55_fu_135_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv3_i11_i115_i_cast_fu_117_p1 = conv3_i11_i115_i;

assign conv3_i11_i71_i_cast_fu_113_p1 = conv3_i11_i71_i;

assign grp_fu_186_p0 = grp_fu_186_p00;

assign grp_fu_186_p00 = N_2_q0;

assign grp_fu_186_p1 = conv3_i11_i71_i_cast_reg_213;

assign grp_fu_192_p0 = grp_fu_192_p00;

assign grp_fu_192_p00 = N_1_q0;

assign grp_fu_192_p1 = conv3_i11_i115_i_cast_reg_218;

assign icmp_ln55_fu_129_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign round_up_fu_159_p3 = grp_fu_192_p3[32'd7];

assign trunc_ln3_fu_170_p4 = {{grp_fu_192_p3[15:8]}};

assign zext_ln55_fu_141_p1 = ap_sig_allocacmp_i_1;

assign zext_ln58_fu_166_p1 = round_up_fu_159_p3;

always @ (posedge ap_clk) begin
    conv3_i11_i71_i_cast_reg_213[15:8] <= 8'b00000000;
    conv3_i11_i115_i_cast_reg_218[15:8] <= 8'b00000000;
    zext_ln55_reg_227[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_227_pp0_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_227_pp0_iter2_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_227_pp0_iter3_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_227_pp0_iter4_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_55_1
