// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        A_4_address0,
        A_4_ce0,
        A_4_q0,
        A_5_address0,
        A_5_ce0,
        A_5_q0,
        A_6_address0,
        A_6_ce0,
        A_6_q0,
        A_7_address0,
        A_7_ce0,
        A_7_q0,
        conv3_i11_i_i546,
        conv3_i11_i_i546_1,
        conv3_i11_i_i546_2,
        conv3_i11_i_i546_3,
        conv3_i11_i_i546_4,
        conv3_i11_i_i546_5,
        conv3_i11_i_i546_6,
        conv3_i11_i_i546_7,
        N_2_address0,
        N_2_ce0,
        N_2_we0,
        N_2_d0,
        ACTIVATION_FUNC_LUT_VEC_address0,
        ACTIVATION_FUNC_LUT_VEC_ce0,
        ACTIVATION_FUNC_LUT_VEC_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] A_address0;
output   A_ce0;
input  [7:0] A_q0;
output  [5:0] A_1_address0;
output   A_1_ce0;
input  [7:0] A_1_q0;
output  [5:0] A_2_address0;
output   A_2_ce0;
input  [7:0] A_2_q0;
output  [5:0] A_3_address0;
output   A_3_ce0;
input  [7:0] A_3_q0;
output  [5:0] A_4_address0;
output   A_4_ce0;
input  [7:0] A_4_q0;
output  [5:0] A_5_address0;
output   A_5_ce0;
input  [7:0] A_5_q0;
output  [5:0] A_6_address0;
output   A_6_ce0;
input  [7:0] A_6_q0;
output  [5:0] A_7_address0;
output   A_7_ce0;
input  [7:0] A_7_q0;
input  [7:0] conv3_i11_i_i546;
input  [7:0] conv3_i11_i_i546_1;
input  [7:0] conv3_i11_i_i546_2;
input  [7:0] conv3_i11_i_i546_3;
input  [7:0] conv3_i11_i_i546_4;
input  [7:0] conv3_i11_i_i546_5;
input  [7:0] conv3_i11_i_i546_6;
input  [7:0] conv3_i11_i_i546_7;
output  [5:0] N_2_address0;
output   N_2_ce0;
output   N_2_we0;
output  [7:0] N_2_d0;
output  [7:0] ACTIVATION_FUNC_LUT_VEC_address0;
output   ACTIVATION_FUNC_LUT_VEC_ce0;
input  [7:0] ACTIVATION_FUNC_LUT_VEC_q0;

reg ap_idle;
reg A_ce0;
reg A_1_ce0;
reg A_2_ce0;
reg A_3_ce0;
reg A_4_ce0;
reg A_5_ce0;
reg A_6_ce0;
reg A_7_ce0;
reg N_2_ce0;
reg N_2_we0;
reg ACTIVATION_FUNC_LUT_VEC_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_303_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [15:0] conv3_i11_i_i546_7_cast_fu_263_p1;
reg   [15:0] conv3_i11_i_i546_7_cast_reg_476;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] conv3_i11_i_i546_6_cast_fu_267_p1;
reg   [15:0] conv3_i11_i_i546_6_cast_reg_481;
wire   [15:0] conv3_i11_i_i546_5_cast_fu_271_p1;
reg   [15:0] conv3_i11_i_i546_5_cast_reg_486;
wire   [15:0] conv3_i11_i_i546_4_cast_fu_275_p1;
reg   [15:0] conv3_i11_i_i546_4_cast_reg_491;
wire   [15:0] conv3_i11_i_i546_3_cast_fu_279_p1;
reg   [15:0] conv3_i11_i_i546_3_cast_reg_496;
wire   [15:0] conv3_i11_i_i546_2_cast_fu_283_p1;
reg   [15:0] conv3_i11_i_i546_2_cast_reg_501;
wire   [15:0] conv3_i11_i_i546_1_cast_fu_287_p1;
reg   [15:0] conv3_i11_i_i546_1_cast_reg_506;
wire   [15:0] conv3_i11_i_i546_cast_fu_291_p1;
reg   [15:0] conv3_i11_i_i546_cast_reg_511;
wire   [63:0] zext_ln33_fu_315_p1;
reg   [63:0] zext_ln33_reg_520;
reg   [63:0] zext_ln33_reg_520_pp0_iter1_reg;
reg   [63:0] zext_ln33_reg_520_pp0_iter2_reg;
reg   [63:0] zext_ln33_reg_520_pp0_iter3_reg;
reg   [63:0] zext_ln33_reg_520_pp0_iter4_reg;
wire   [15:0] sum_fu_348_p2;
wire   [15:0] mul_ln39_fu_357_p2;
wire   [15:0] mul_ln39_3_fu_366_p2;
wire   [15:0] mul_ln39_4_fu_375_p2;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln44_fu_432_p1;
reg   [6:0] i_1_fu_80;
wire   [6:0] add_ln33_fu_309_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i;
wire   [7:0] sum_fu_348_p0;
wire   [7:0] sum_fu_348_p1;
wire   [7:0] mul_ln39_fu_357_p0;
wire   [7:0] mul_ln39_fu_357_p1;
wire   [7:0] mul_ln39_3_fu_366_p0;
wire   [7:0] mul_ln39_3_fu_366_p1;
wire   [7:0] mul_ln39_4_fu_375_p0;
wire   [7:0] mul_ln39_4_fu_375_p1;
wire   [15:0] grp_fu_445_p3;
wire   [15:0] grp_fu_453_p3;
wire   [15:0] grp_fu_461_p3;
wire   [15:0] grp_fu_437_p3;
(* use_dsp48 = "no" *) wire   [15:0] add_ln39_5_fu_384_p2;
(* use_dsp48 = "no" *) wire   [15:0] add_ln39_2_fu_380_p2;
wire   [15:0] sum_1_fu_388_p2;
wire   [0:0] tmp_fu_404_p3;
wire   [0:0] xor_ln44_fu_412_p2;
wire   [7:0] select_ln44_fu_418_p3;
wire   [7:0] trunc_ln44_2_fu_394_p4;
wire   [7:0] add_ln44_fu_426_p2;
wire   [7:0] grp_fu_437_p0;
wire   [7:0] grp_fu_437_p1;
wire   [7:0] grp_fu_445_p0;
wire   [7:0] grp_fu_445_p1;
wire   [7:0] grp_fu_453_p0;
wire   [7:0] grp_fu_453_p1;
wire   [7:0] grp_fu_461_p0;
wire   [7:0] grp_fu_461_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_437_p00;
wire   [15:0] grp_fu_445_p00;
wire   [15:0] grp_fu_453_p00;
wire   [15:0] grp_fu_461_p00;
wire   [15:0] mul_ln39_3_fu_366_p00;
wire   [15:0] mul_ln39_4_fu_375_p00;
wire   [15:0] mul_ln39_fu_357_p00;
wire   [15:0] sum_fu_348_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 i_1_fu_80 = 7'd0;
#0 ap_done_reg = 1'b0;
end

mlp_nn_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U46(
    .din0(sum_fu_348_p0),
    .din1(sum_fu_348_p1),
    .dout(sum_fu_348_p2)
);

mlp_nn_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U47(
    .din0(mul_ln39_fu_357_p0),
    .din1(mul_ln39_fu_357_p1),
    .dout(mul_ln39_fu_357_p2)
);

mlp_nn_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U48(
    .din0(mul_ln39_3_fu_366_p0),
    .din1(mul_ln39_3_fu_366_p1),
    .dout(mul_ln39_3_fu_366_p2)
);

mlp_nn_HLS_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U49(
    .din0(mul_ln39_4_fu_375_p0),
    .din1(mul_ln39_4_fu_375_p1),
    .dout(mul_ln39_4_fu_375_p2)
);

mlp_nn_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_437_p0),
    .din1(grp_fu_437_p1),
    .din2(mul_ln39_fu_357_p2),
    .ce(1'b1),
    .dout(grp_fu_437_p3)
);

mlp_nn_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_445_p0),
    .din1(grp_fu_445_p1),
    .din2(mul_ln39_3_fu_366_p2),
    .ce(1'b1),
    .dout(grp_fu_445_p3)
);

mlp_nn_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_453_p0),
    .din1(grp_fu_453_p1),
    .din2(mul_ln39_4_fu_375_p2),
    .ce(1'b1),
    .dout(grp_fu_453_p3)
);

mlp_nn_HLS_mac_muladd_8ns_8ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_16ns_16_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_461_p0),
    .din1(grp_fu_461_p1),
    .din2(sum_fu_348_p2),
    .ce(1'b1),
    .dout(grp_fu_461_p3)
);

mlp_nn_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_303_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_80 <= add_ln33_fu_309_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_80 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv3_i11_i_i546_1_cast_reg_506[7 : 0] <= conv3_i11_i_i546_1_cast_fu_287_p1[7 : 0];
        conv3_i11_i_i546_2_cast_reg_501[7 : 0] <= conv3_i11_i_i546_2_cast_fu_283_p1[7 : 0];
        conv3_i11_i_i546_3_cast_reg_496[7 : 0] <= conv3_i11_i_i546_3_cast_fu_279_p1[7 : 0];
        conv3_i11_i_i546_4_cast_reg_491[7 : 0] <= conv3_i11_i_i546_4_cast_fu_275_p1[7 : 0];
        conv3_i11_i_i546_5_cast_reg_486[7 : 0] <= conv3_i11_i_i546_5_cast_fu_271_p1[7 : 0];
        conv3_i11_i_i546_6_cast_reg_481[7 : 0] <= conv3_i11_i_i546_6_cast_fu_267_p1[7 : 0];
        conv3_i11_i_i546_7_cast_reg_476[7 : 0] <= conv3_i11_i_i546_7_cast_fu_263_p1[7 : 0];
        conv3_i11_i_i546_cast_reg_511[7 : 0] <= conv3_i11_i_i546_cast_fu_291_p1[7 : 0];
        zext_ln33_reg_520[6 : 0] <= zext_ln33_fu_315_p1[6 : 0];
        zext_ln33_reg_520_pp0_iter1_reg[6 : 0] <= zext_ln33_reg_520[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        zext_ln33_reg_520_pp0_iter2_reg[6 : 0] <= zext_ln33_reg_520_pp0_iter1_reg[6 : 0];
        zext_ln33_reg_520_pp0_iter3_reg[6 : 0] <= zext_ln33_reg_520_pp0_iter2_reg[6 : 0];
        zext_ln33_reg_520_pp0_iter4_reg[6 : 0] <= zext_ln33_reg_520_pp0_iter3_reg[6 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ACTIVATION_FUNC_LUT_VEC_ce0 = 1'b1;
    end else begin
        ACTIVATION_FUNC_LUT_VEC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_2_ce0 = 1'b1;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_3_ce0 = 1'b1;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_4_ce0 = 1'b1;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_5_ce0 = 1'b1;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_6_ce0 = 1'b1;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_7_ce0 = 1'b1;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        N_2_ce0 = 1'b1;
    end else begin
        N_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        N_2_we0 = 1'b1;
    end else begin
        N_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_303_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 7'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_80;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ACTIVATION_FUNC_LUT_VEC_address0 = zext_ln44_fu_432_p1;

assign A_1_address0 = zext_ln33_reg_520_pp0_iter1_reg;

assign A_2_address0 = zext_ln33_fu_315_p1;

assign A_3_address0 = zext_ln33_fu_315_p1;

assign A_4_address0 = zext_ln33_reg_520_pp0_iter1_reg;

assign A_5_address0 = zext_ln33_reg_520_pp0_iter1_reg;

assign A_6_address0 = zext_ln33_fu_315_p1;

assign A_7_address0 = zext_ln33_fu_315_p1;

assign A_address0 = zext_ln33_reg_520_pp0_iter1_reg;

assign N_2_address0 = zext_ln33_reg_520_pp0_iter4_reg;

assign N_2_d0 = ACTIVATION_FUNC_LUT_VEC_q0;

assign add_ln33_fu_309_p2 = (ap_sig_allocacmp_i + 7'd1);

assign add_ln39_2_fu_380_p2 = (grp_fu_445_p3 + grp_fu_453_p3);

assign add_ln39_5_fu_384_p2 = (grp_fu_461_p3 + grp_fu_437_p3);

assign add_ln44_fu_426_p2 = (select_ln44_fu_418_p3 + trunc_ln44_2_fu_394_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv3_i11_i_i546_1_cast_fu_287_p1 = conv3_i11_i_i546_1;

assign conv3_i11_i_i546_2_cast_fu_283_p1 = conv3_i11_i_i546_2;

assign conv3_i11_i_i546_3_cast_fu_279_p1 = conv3_i11_i_i546_3;

assign conv3_i11_i_i546_4_cast_fu_275_p1 = conv3_i11_i_i546_4;

assign conv3_i11_i_i546_5_cast_fu_271_p1 = conv3_i11_i_i546_5;

assign conv3_i11_i_i546_6_cast_fu_267_p1 = conv3_i11_i_i546_6;

assign conv3_i11_i_i546_7_cast_fu_263_p1 = conv3_i11_i_i546_7;

assign conv3_i11_i_i546_cast_fu_291_p1 = conv3_i11_i_i546;

assign grp_fu_437_p0 = grp_fu_437_p00;

assign grp_fu_437_p00 = A_2_q0;

assign grp_fu_437_p1 = conv3_i11_i_i546_2_cast_reg_501;

assign grp_fu_445_p0 = grp_fu_445_p00;

assign grp_fu_445_p00 = A_3_q0;

assign grp_fu_445_p1 = conv3_i11_i_i546_3_cast_reg_496;

assign grp_fu_453_p0 = grp_fu_453_p00;

assign grp_fu_453_p00 = A_6_q0;

assign grp_fu_453_p1 = conv3_i11_i_i546_6_cast_reg_481;

assign grp_fu_461_p0 = grp_fu_461_p00;

assign grp_fu_461_p00 = A_7_q0;

assign grp_fu_461_p1 = conv3_i11_i_i546_7_cast_reg_476;

assign icmp_ln33_fu_303_p2 = ((ap_sig_allocacmp_i == 7'd64) ? 1'b1 : 1'b0);

assign mul_ln39_3_fu_366_p0 = mul_ln39_3_fu_366_p00;

assign mul_ln39_3_fu_366_p00 = A_4_q0;

assign mul_ln39_3_fu_366_p1 = conv3_i11_i_i546_4_cast_reg_491;

assign mul_ln39_4_fu_375_p0 = mul_ln39_4_fu_375_p00;

assign mul_ln39_4_fu_375_p00 = A_5_q0;

assign mul_ln39_4_fu_375_p1 = conv3_i11_i_i546_5_cast_reg_486;

assign mul_ln39_fu_357_p0 = mul_ln39_fu_357_p00;

assign mul_ln39_fu_357_p00 = A_1_q0;

assign mul_ln39_fu_357_p1 = conv3_i11_i_i546_1_cast_reg_506;

assign select_ln44_fu_418_p3 = ((xor_ln44_fu_412_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sum_1_fu_388_p2 = (add_ln39_5_fu_384_p2 + add_ln39_2_fu_380_p2);

assign sum_fu_348_p0 = sum_fu_348_p00;

assign sum_fu_348_p00 = A_q0;

assign sum_fu_348_p1 = conv3_i11_i_i546_cast_reg_511;

assign tmp_fu_404_p3 = sum_1_fu_388_p2[32'd7];

assign trunc_ln44_2_fu_394_p4 = {{sum_1_fu_388_p2[15:8]}};

assign xor_ln44_fu_412_p2 = (tmp_fu_404_p3 ^ 1'd1);

assign zext_ln33_fu_315_p1 = ap_sig_allocacmp_i;

assign zext_ln44_fu_432_p1 = add_ln44_fu_426_p2;

always @ (posedge ap_clk) begin
    conv3_i11_i_i546_7_cast_reg_476[15:8] <= 8'b00000000;
    conv3_i11_i_i546_6_cast_reg_481[15:8] <= 8'b00000000;
    conv3_i11_i_i546_5_cast_reg_486[15:8] <= 8'b00000000;
    conv3_i11_i_i546_4_cast_reg_491[15:8] <= 8'b00000000;
    conv3_i11_i_i546_3_cast_reg_496[15:8] <= 8'b00000000;
    conv3_i11_i_i546_2_cast_reg_501[15:8] <= 8'b00000000;
    conv3_i11_i_i546_1_cast_reg_506[15:8] <= 8'b00000000;
    conv3_i11_i_i546_cast_reg_511[15:8] <= 8'b00000000;
    zext_ln33_reg_520[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln33_reg_520_pp0_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln33_reg_520_pp0_iter2_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln33_reg_520_pp0_iter3_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln33_reg_520_pp0_iter4_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp_nn_HLS_mlp_nn_HLS_Pipeline_VITIS_LOOP_33_11
